### ISSUE TITLE
Phonon DOS issue 

### ISSUE THREAD

**Issue by sajidurehman** [SMTG-UCL/sumo#102]
Hi Adam,
             I am try to generate phonon DOS by following command 
Command : sumo-phonon-bandplot --dos -f FORCE_CONSTANTS 

I am only getting phonon_band.dat file but not Phonopy .dat file for phonon DOS. Could you please guide me how to fix this issue.

Regards
Sajid

**Comment by ajjackson** [comment]
Hi Sajid,

you need to specify a sampling mesh for Phonopy to evaluate the DOS on. This is why we don't do it automatically; the user has to decide what is a suitable mesh density for their system. For the RbSnI6 test data folder I can generate a `total_dos.dat` file with

```bash
phonopy --dim 3 3 2 --dos --mesh 16 16 16
```

**Comment by sajidurehman** [comment]
Thank you for reply. Is there any way to use sumo-phonon-bandplot command and generate total_dos.dat file without using phonopy directly?

**Comment by ajjackson** [comment]
Not at present, I'm afraid. It is expected that Sumo users are familiar with Phonopy if they already have FORCE_CONSTANTS/FORCE_SETS data.

Providing "convenience" flags in Sumo that are passed to Phonopy adds a lot of maintenance burden; the Phonopy API is under constant development.

I suggest that if you need to do this frequently you create a bash shell function that generates the .dat file before calling Phonopy. I gave another example of turning a multi-step personal workflow into a shell function in https://github.com/SMTG-UCL/sumo/issues/97#issuecomment-601227311 .
