### ISSUE TITLE
bandstats issue

### ISSUE THREAD

**Issue by fronzi** [SMTG-UCL/sumo#104]
I am trying to run sumo but I get an error. I installed all the dependencies indicated in 
https://sumo.readthedocs.io/en/latest/index.html
and I run any of the sumo the codes (sumo-*) in the VASP folder that includes all the standard output files after band structure calculations. 
However, I obtain this error message:

---------------------
Traceback (most recent call last):
File "/Users/Marco/opt/anaconda3/bin/sumo-bandstats", line 10, in <module>
sys.exit(main())
File "/Users/Marco/opt/anaconda3/lib/python3.7/site-packages/sumo/cli/bandstats.py", line 326, in main
  parabolic=args.nonparabolic)
  File "/Users/Marco/opt/anaconda3/lib/python3.7/site-packages/sumo/cli/bandstats.py", line 93, in bandstats
    bs = vr.get_band_structure(line_mode=True)
  File "/Users/Marco/opt/anaconda3/lib/python3.7/site-packages/pymatgen/io/vasp/outputs.py", line 858, in get_band_structure
    if '' in kpoint_file.labels:
TypeError: argument of type 'NoneType' is not iterable------------------

I am wondering if you experienced this problem and maybe know how to solve it. 
Thanks

**Comment by utf** [comment]
You should only run sumo-bandstats on line mode band structure calculations. For example using KPOINTS files generated by sumo-kgen. You can see the documentation for using kgen here: https://sumo.readthedocs.io/en/latest/sumo-kgen.html

If your calculation WAS on a high-symmetry path, just not one generated by sumo, you can edit the KPOINTS file to manually include the k-point labels for the high symmetry points. For example, the line containing the gamma k-point:
```
0 0 0
```
Would be changed to:
```
0 0 0 \Gamma
```

**Comment by ajjackson** [comment]
Hi @fronzi  can you confirm if this solved your problem?

**Comment by fronzi** [comment]
> Hi @fronzi can you confirm if this solved your problem?

Hi @ajjackson , yes this solved the problem
