### ISSUE TITLE
Spin channels as a subplot with extra customisation

### ISSUE THREAD

**Issue by NellieAT** [SMTG-UCL/sumo#109]
Hi, Firstly, thanks Alex and Adam for the sumo program, its very helpful!
 
Disclaimer - I'm new to this program, so apologies if this is repetition (I may have missed it from the documentation (1.1.0) that was published in Jan 2020)

I know you can separate out elements into subplots, **(1)** but is there a way to do that with spin-up spin-down channels, i.e. have 2 subplots together in 1 graphic? **(2)** can we also specify which elements are shown in each of those spin channel subplots?  

Thanks

**Comment by ajjackson** [comment]
Hi Nellie,

at the moment, the workaround for this is to create two plot images, one with `--spin=up` and one with `--spin=down`, and then combine them into a figure in the manuscript/report. You should be able to combine this with the `atoms`/`elements` options as normal to control which elements/atoms/orbitals appear.

We would like to have a more general system for composing arbitrary subplot setups; there are _so many_ useful combinations that we can't offer dedicated options for all of them. The trouble is finding the time for a deep discussion / code sprint to hammer it out...

**Comment by NellieAT** [comment]
Hi Adam,

Thanks for the quick response,

OK, yep will do them separately as suggested. 

Sure, I can imagine! Just thought I'd double check to make sure I didn't miss a trick.  

KR,

Nell

**Comment by ajjackson** [comment]
Closing as solved. Feel free to reopen for further discussion if needed.
