### ISSUE TITLE
Phonon bandplot, --density tag not working

### ISSUE THREAD

**Issue by dgaines2** [SMTG-UCL/sumo#111]
I wanted to change the density of qpoints along high-symmetry paths in the phonon bandstructure, but it seems that the --density tag has no effect, and 'nqpoint' in sumo_band.yaml is the same regardless of the input.

**Comment by utf** [comment]
I just pushed a fix to the GitHub, can you let me know if it works for you.

**Comment by dgaines2** [comment]
Seems to be working for me, thank you Alex!
