### ISSUE TITLE
Tests failing — missing Si8.json file

### ISSUE THREAD

**Issue by utf** [SMTG-UCL/sumo#112]
Hi @ajjackson, do you know where this file has gone? `sumo/tests/data/Si/Si8.json`

See https://travis-ci.org/github/SMTG-UCL/sumo/jobs/716249491

**Comment by ajjackson** [comment]
I suspect a PEBKAC error on my end :disappointed:

**Comment by utf** [comment]
Ha, thanks for fixing 👍
