### ISSUE TITLE
times new roman font

### ISSUE THREAD

**Issue by OkiPVP** [SMTG-UCL/sumo#116]
Hello everyone, 
This is my first post. I'm trying to plot DoS with Times New Roman font, i write in the command window '--font "times new roman"' and the output is the DoS plot with the actual TNR font but in **Bold**. I don't know if anyone had this problem but i can't solve it, maybe it's a bug.

Thanks
[dos.pdf](https://github.com/SMTG-UCL/sumo/files/5126460/dos.pdf)

**Comment by utf** [comment]
Hi, I'm unable to reproduce this bug. When I run `sumo-dosplot --font "Times New Roman"` I get the correct font (see attached image).

I would suggest trying the same capitalisation as above or checking your system fonts.

[dos.pdf](https://github.com/SMTG-UCL/sumo/files/5388710/dos.pdf)
