### ISSUE TITLE
I find a bug while using sumo-bandstats

### ISSUE THREAD

**Issue by 1995hanjian** [SMTG-UCL/sumo#12]
- While I run ‘sumo-bandstats’，it reports that:
```
Indirect band gap: 0.609 eV
Traceback (most recent call last):
  File "/usr/local/bin/sumo-bandstats", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/sumo/cli/bandstats.py", line 320, in main
    parabolic=args.nonparabolic)
  File "/usr/local/lib/python3.5/site-packages/sumo/cli/bandstats.py", line 101, in bandstats
    _log_band_gap_information(bs)
  File "/usr/local/lib/python3.5/site-packages/sumo/cli/bandstats.py", line 178, in _log_band_gap_information
    direct_bg = direct_data[spins[0]]['value']
TypeError: 'dict_keys' object does not support indexing
```

- Then I changed several part of bandstats.py, and it runs successfully. 

- My changes are:
`line 178:         direct_bg = direct_data[list(spins)[0]]['value']`
`line 181:         for spin in direct_data.keys():`
`line 221:                      + '({})'.format(spin.name) for spin in spins]`

- But I don't know whether this change is correct. To be honest, I don't know the details in the code.  Could you help me to fix the problem? Thanks a lot.

**Comment by ajjackson** [comment]
Thank you for reporting this! We have pushed a [quick fix](https://github.com/SMTG-UCL/sumo/commit/487aa809f549f2e34fa899db79fda88001d8f64b) (quite similar to yours) to the Github master branch and plan to make another small adjustment before this is released properly.
