### ISSUE TITLE
Docs issues: header not updating with releases, some missing content

### ISSUE THREAD

**Issue by ajjackson** [SMTG-UCL/sumo#121]
Spotted by @brlec

The header still shows as "sumo 1.1.0 documentation" even though the changelog reflects version 2.0.2

Some docstring content seems to be missing. Compare https://smtg-ucl.github.io/sumo/sumo.plotting.html#sumo.plotting.bs_plotter.SBSPlotter.get_plot to https://github.com/SMTG-UCL/sumo/blob/692910230ac237189e2158f5955cb862af22a048/sumo/plotting/bs_plotter.py#L63

and it looks like the docstring of this method has been entirely replaced by the one from Pymatgen, missing e.g. the `dos_options` argument.

**Comment by utf** [comment]
Good catches. These must both have been broken for quite a while.

Docs version is now automatically set from sumo version: d02605a7f5539b56dc26c7beeaa99d83e8dd1879

The docstring was more tricky to diagnose. It actually comes from the `styled_plot` decorator which wipes out the underlying docstring. [The trick](https://stackoverflow.com/questions/1782843/python-decorator-handling-docstrings) was to use `functools.wrap` to preserve the underlying docstring: c4496bb76b993dc48d3cf33ced8d0317cbbad355
