### ISSUE TITLE
sumo-bandplot

### ISSUE THREAD

**Issue by lavanganes** [SMTG-UCL/sumo#122]
Hi Alex,
I had an issue with the sumo-bandplot it gave the following error:

```Traceback (most recent call last):
  File "/home/miniconda3/envs/toolbox/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/toolbox/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 568, in main
    bandplot(filenames=args.filenames, code=args.code, prefix=args.prefix,
  File "/home/miniconda3/envs/toolbox/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 328, in bandplot
    plt = plotter.get_plot(
  File "/home/miniconda3/envs/toolbox/lib/python3.8/site-packages/sumo/plotting/__init__.py", line 61, in wrapper
    return get_plot(*args, **kwargs)
  File "/home/miniconda3/envs/toolbox/lib/python3.8/site-packages/sumo/plotting/bs_plotter.py", line 190, in get_plot
    else eners[str(Spin.up)][nd][nb]
TypeError: list indices must be integers or slices, not str
```
I then did `pip install sumo==1.4.0` which allowed for it to work. 

Just wanted to notify you of the bug.

Thanks,

Lavan

**Comment by ajjackson** [comment]
I suspect this can also be fixed by using a very recent version of pymatgen, as there was an API change in this area. But we should clear this up from the Sumo end, either by changing our requirements or providing logic based on the Pymatgen version.

**Comment by utf** [comment]
Thanks for raising this.

@ajjackson The simplest fix would be to just bump the pymatgen version requirement to the latest version. Do you see any issue with this?

**Comment by ajjackson** [comment]
Not especially bothered about the pymatgen requirement specifically, but that has a knock-on effect on our other minimum requirements. Our setup.py could use some work; I think we already agreed to require Py3.6 and we should really
- specify miminum versions for the other packages
- test against those versions
- also test against the latest versions on PyPI

"Old libs" tests have proven very useful for other projects I'm involved in. Ideally we'd also have a test hook that fires off whenever Pymatgen releases a new version, as that's often the culprit for breakage.

I do worry that pymatgen moves too quickly for many Sumo users, so this cannot _always_ be the solution. But as a cleanup is in order I suppose it's ok if that bumps a few requirements (within contraints of Python 3.6?)

**Comment by utf** [comment]
What I've generally done in other packages is use a requirements.txt file that specifies the exact version numbers of dependencies. This is kept up to date using dependabot which will automatically submit a PR whenever a new version of any of the dependences is released. Continuous integration then tests on the versions specified in requirements.txt, so we will always have a set of dependencies that will produce a working version of sumo.

In setup.py, we can then only specify the minimum oldest versions that are absolutely required to run sumo. That way people installing using pip don't run into dependency hell.

How to test those minimum oldest versions is not clear to me currently, we could also maintain a separate requirements-minimum.txt but that seems painful.

**Comment by ajjackson** [comment]
ASE uses Dockerfiles with a somewhat custom test framework: https://gitlab.com/ase/ase-dockers

Euphonic uses Jenkins/Tox with multiple requirements files https://github.com/pace-neutrons/Euphonic/blob/master/tox.ini

Mantid uses Jenkins to run tests on quite a range of machines.

I suppose what these all have in common is that they are not using Travis. But I think it is possible using the `jobs` feature to install different requirements files: https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems We just need to make sure that the sumo install step does not then upgrade anything unnecessarily.

There's also this feature which could maybe be used to select different requirements files: https://docs.travis-ci.com/user/languages/python/#testing-against-multiple-versions-of-dependencies-eg-django-or-flask

**Comment by utf** [comment]
I think we could do multiple python package environments just by using a couple of requirements.txt files + dependabot to keep one up-to-date.

I will look at implementing this.

In the meantime, sumo is now python 3.6+ only and I've bumped the pymatgen requirement to the latest version.
