### ISSUE TITLE
Issue plotting band structure.

### ISSUE THREAD

**Issue by SebastianGelvesB** [SMTG-UCL/sumo#125]
Hi, I have been struggling when trying to plot the projected per element band structure for systems with more than 3 elements. It gives me the error that the default mode 'RGB' only supports up to 3 elements. Is there a way to plot the projected band structure for more than 3 elements? 
On the other hand, I was wondering if it's possible to make the vertical lines in the k-points dotted instead of solid?

Thank you so much.

**Comment by utf** [comment]
You can use "stacked" mode to plot more than 3 projections. Search for "stacked" in the documentation: https://smtg-ucl.github.io/sumo/sumo-bandplot.html#projected-band-structures

You can customise sumo plots using a matplotlib style sheet. See the docs here: https://smtg-ucl.github.io/sumo/customising-plots.html and the matplotlib docs here: https://matplotlib.org/tutorials/introductory/customizing.html

To control the grid line style you should make a file called `mystyle.mplstyle` with the following contents:
```
grid.linestyle: :  # dotted line style, other options are dashed "--", dash dotted, "-." or solid "-". 
```
And then select that style when using bandplot:
```
sumo-bandplot --style mystyle.mplstyle
```

Please note, I just pushed a new version (v2.1.1) that allows customising the vertical lines, so you should make sure to update sumo before plotting.
