### ISSUE TITLE
Colors in band structure

### ISSUE THREAD

**Issue by SebastianGelvesB** [SMTG-UCL/sumo#126]
Dear Developers,

I would like to ask if is it possible to control the colors of the band structure just as in the dos plot. I would like to plot the projected band structure per element for my system, assigning to each element the color that you get on VESTA when visualizing the structure. 
I also was wondering if is it possible to set fermi to zero regardless if the material is insulator or metallic.

Thank you so much for your help.

**Comment by utf** [comment]
1. To edit the colours in the stacked projected band structure, you need to edit the sumo source code directly. Specifically, here is where the projection colours are set: https://github.com/SMTG-UCL/sumo/blob/d21ab01030f2a0c65f462d54c835dc32b505e5e0/sumo/plotting/bs_plotter.py#L456

2. No, this is not currently possible. The Fermi level from VASP is meaningless if the system is an insulator.
