### ISSUE TITLE
 Plotting DOS from two vasprun files

### ISSUE THREAD

**Issue by JaafarMehrez** [SMTG-UCL/sumo#127]
I would like to ask if there is a feature in sumo-dosplot where i can draw the DOS of two materials obtained by separate vasprun files, so that I could combine them in one figure for better comparison. 
If such functional is not supported, I would appreciate the guidance to get it done with sumo. 
Thank You

**Comment by ajjackson** [comment]
Hi Jaafar,

we don't provide this kind of thing at the moment but I might be able to help you get something useful. A figure with two PDOS on the same axes would be quite cluttered and difficult to interpret. Are you looking to plot two orbital-projected DOS on separate subplots within the same figure, or are you looking to plot two total DOS lines on the same set of axes?

**Comment by JaafarMehrez** [comment]
Thank for your reply, actually I am looking for two TDOS lines on the same set of axes. So if you have any suggestions or at least a starting point in the source code, that would be great :+1:

**Comment by ajjackson** [comment]
As you are using Vasp the simplest thing might be to use the underlying Pymatgen features 
Sumo is calling. With a little craftiness you can still make use of Sumo's styling!

I don't have the files lying around to test this so there may be some errors in the sample code below, but hopefully it will be enough to get you going :smile: 

To get the DOS for each file using Pymatgen:

```python
from pymatgen.io.vasp.outputs import Vasprun
my_vasprun_files = ('/path/to/first/vasprun.xml', '/path/to/second/vasprun.xml') 
vasp_data = [Vasprun(filename) for filename in my_vasprun_files]

dos_list = [vasprun.complete_dos for vasprun in vasp_data]
```

The DOS data is in a pymatgen class from `pymatgen.electronic_structure.dos`, which can be broadened and converted to dict objects indexed by spin:

```python
import numpy as np
sigma = 0.2
broad_spin_resolved_dos_list = [dos.get_smeared_densities(sigma) for dos in dos_list]
broad_total_dos_list = [np.sum([dos[spin] for spin in dos], axis=0)
                        for dos in broad_spin_resolved_dos_list]

```

Now you have some simple arrays that will work with matplotlib. The last trick is to steal sumo's stylesheets while plotting the data:
```python
import matplotlib.pyplot as plt
import matplotlib.style
from sumo.plotting import sumo_base_style, sumo_dos_style

fig, ax = plt.subplot()
with matplotlib.style.context([sumo_base_style, sumo_dos_style]):
    for dos, broad_densities in zip(dos_list, broad_total_dos_list):
        ax.plot(dos.energies, broad_densities)

plt.show()
```

With the usual matplotlib jiggling you should be able to get a nice plot!

**Comment by JaafarMehrez** [comment]
Thank you, I think that would work out for me.. I am giving a try.

**Comment by ajjackson** [comment]
How did you get on?

**Comment by ajjackson** [comment]
Closing for now, you should still be able to comment if there's a follow-up.

**Comment by JaafarMehrez** [comment]
Sorry for the late reply. Yes I have tried what you have suggested and it worked pretty fine
