### ISSUE TITLE
Support matplotlib styles

### ISSUE THREAD

**Issue by ajjackson** [SMTG-UCL/sumo#13]
Matplotlib provides a framework for visual styles. At the moment this doesn't behave as expected with `sumo` because of the customised colour management. If we made more direct use of style sheets then we could have, e.g. `sumo-bandplot --style=dark_background` to use https://matplotlib.org/gallery/style_sheets/dark_background.html .

**Comment by utf** [comment]
It would be nice to have a precedence for style sheet usage.

For example: `--style` > `~/.sumo.mplstyle` > default sumo style sheet.

Additionally, what are your thoughts about overriding only specific settings. For example, if your style only contains `axes.labelsize : 20`, is there a mechanism to use the rest of the settings defined in the sumo style sheet?

Or are we expecting people to copy and paste the whole sumo style and only change the bits they want?

**Comment by utf** [comment]
Implemented in #19.
