### ISSUE TITLE
Band structure with dotted horizontal labelling at Fermi label   

### ISSUE THREAD

**Issue by subhadipniser333** [SMTG-UCL/sumo#135]
Hey how can I give a horizontal dotted line at the fermi label in the band plot just like below. is there any tool?

![Band-structure-of-GaN-in-the-wurtzite-structure-The-Fermi-energy-is-set-to-0-eV-The](https://user-images.githubusercontent.com/83715114/117161954-fbdfea00-addf-11eb-93b3-43cba8320b67.jpg)

**Comment by kcbhamu** [comment]
> Hey how can I give a horizontal dotted line at the fermi label in the band plot just like below. is there any tool?
> 
> ![Band-structure-of-GaN-in-the-wurtzite-structure-The-Fermi-energy-is-set-to-0-eV-The](https://user-images.githubusercontent.com/83715114/117161954-fbdfea00-addf-11eb-93b3-43cba8320b67.jpg)

I am also looking for a reply on the same query.

**Comment by linton1995** [comment]
How to put horizontal line

**Comment by ajjackson** [comment]
This has been implemented in #68 ; for now it can be accessed with a developer install, and it will be in the next release version.

**Comment by ajjackson** [comment]
(Thank you all for letting us know you needed this feature; I have not had much time to work on Sumo in the last couple of years and it was helpful to know what request is most popular.)
