### ISSUE TITLE
sumo-bandplot

### ISSUE THREAD

**Issue by andreangletti** [SMTG-UCL/sumo#141]
I get this error when I try to plot the band structure of two dimensional monolayer. No problem with the dos plot. The calculation are not spin polarized on linux mint 20.04. I checked and all the depends are present
Traceback (most recent call last):
  File "/fs/home/anand/.local/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/fs/home/anand/.local/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 462, in main
    bandplot(filenames=args.filenames, prefix=args.prefix,
  File "/fs/home/anand/.local/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 246, in bandplot
    plt = plotter.get_plot(zero_to_efermi=True, ymin=ymin, ymax=ymax,
  File "/fs/home/anand/.local/lib/python3.8/site-packages/sumo/plotting/bs_plotter.py", line 136, in get_plot
    if self._bs.is_spin_polarized or self._bs.is_metal():
AttributeError: 'list' object has no attribute 'is_spin_polarized'

**Comment by ajjackson** [comment]
Hi Andrea,

thanks for reporting this. That's a bit strange; this looks like a Pymatgen compatibility issue that was fixed in Sumo a few months ago. Can you confirm which versions of Sumo and Pymatgen you are using?

**Comment by andreangletti** [comment]
Hi, thank you very much for your reply.
I first run 

Requirement already satisfied: sumo in /fs/home/anand/.local/lib/python3.8/site-packages (1.0.6)
... and the same for all the others libraries.
In this way I could not get the path for the executable script like sumo-bandplot so
Then I installed sumo via the command:
pip install sumo==1.0.4
and this is the one I currently running.

**Comment by andreangletti** [comment]
Hi, thank you very much for your reply,
I install again via:
pip install sumo==2.2.5
now it works fine!
