### ISSUE TITLE
Location of sumo is not found

### ISSUE THREAD

**Issue by kcbhamu** [SMTG-UCL/sumo#144]
I have installed sumo using "pip install --user sumo" or in an anaconda environment without any issue.

But I could not file where is the sumo package and how to launch it.

Any help will be appriciated.

**Comment by ajjackson** [comment]
If you used `--user` then it's probably somewhere like `~/.local/bin` which should be added to PATH.

But if you are using Anaconda installed to your user account then you are probably ok to `pip install sumo` without `--user`; the `--user` is there to deal with system permission issues when using a global Python installation.

**Comment by kcbhamu** [comment]
I got below output on terminal but I am still unable to launch sumo

#----------------
**pip3 install --user sumo**

Requirement already satisfied: sumo in /root/.local/lib/python3.7/site-packages
Requirement already satisfied: pymatgen>=2020.10.20 in /root/.local/lib/python3.7/site-packages (from sumo)
Requirement already satisfied: phonopy>=2.1.3 in /root/.local/lib/python3.7/site-packages (from sumo)
Requirement already satisfied: castepxbin==0.1.0 in /root/.local/lib/python3.7/site-packages (from sumo)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from sumo)
Requirement already satisfied: spglib in /usr/local/lib/python3.7/dist-packages (from sumo)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages/matplotlib-3.3.0rc1-py3.7-linux-x86_64.egg (from sumo)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from sumo)
Requirement already satisfied: seekpath in /root/.local/lib/python3.7/site-packages (from sumo)
Requirement already satisfied: h5py in /root/.local/lib/python3.7/site-packages (from sumo)
Requirement already satisfied: typing-extensions>=3.7.4.3; python_version < "3.8" in /root/.local/lib/python3.7/site-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: palettable>=3.1.1 in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: plotly>=4.5.0 in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: ruamel.yaml>=0.15.6 in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: monty>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: sympy in /usr/local/lib/python3.7/dist-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: uncertainties>=3.1.4 in /root/.local/lib/python3.7/site-packages (from pymatgen>=2020.10.20->sumo)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from phonopy>=2.1.3->sumo)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib->sumo)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages/kiwisolver-1.2.0-py3.7-linux-x86_64.egg (from matplotlib->sumo)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages/Pillow-7.2.0-py3.7-linux-x86_64.egg (from matplotlib->sumo)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/lib/python3/dist-packages (from matplotlib->sumo)
Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3/dist-packages (from matplotlib->sumo)
Requirement already satisfied: cached-property; python_version < "3.8" in /root/.local/lib/python3.7/site-packages (from h5py->sumo)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.7/dist-packages (from networkx>=2.2->pymatgen>=2020.10.20->sumo)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly>=4.5.0->pymatgen>=2020.10.20->sumo)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from plotly>=4.5.0->pymatgen>=2020.10.20->sumo)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas->pymatgen>=2020.10.20->sumo)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /usr/local/lib/python3.7/dist-packages (from ruamel.yaml>=0.15.6->pymatgen>=2020.10.20->sumo)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.7/dist-packages (from sympy->pymatgen>=2020.10.20->sumo)
Requirement already satisfied: future in /root/.local/lib/python3.7/site-packages (from uncertainties>=3.1.4->pymatgen>=2020.10.20->sumo)



**I checked the suggested dir and I am having below directories here:**

~/.local/lib/python3.7/site-packages# ls
cached_property-1.5.2.dist-info  future-0.18.2.dist-info  phonopy                       seekpath-2.0.1.dist-info              uncertainties
cached_property.py               h5py                     phonopy-2.11.0.dist-info      sumo                                  uncertainties-3.1.6.dist-info
castepxbin                       h5py-3.3.0.dist-info     __pycache__                   sumo-2.2.5.dist-info
castepxbin-0.1.0.dist-info       libfuturize              pymatgen                      sumo.egg-link
easy-install.pth                 libpasteurize            pymatgen-2022.0.11.dist-info  typing_extensions-3.10.0.0.dist-info
future                           past                     seekpath                      typing_extensions.py

**Comment by ajjackson** [comment]
You used `--user` again. I think with a normal Anaconda setup the simplest option is to `pip install sumo`.

It looks like you have installed Sumo to /root/.local, perhaps there is a bin directory there?

You also seem to have (another?) editable (egg-link) installation in ~/.local/lib. Are you sure there is no ~/.local/bin?

I don't understand how you had permission to write to /root. I've never seen a /root/.local folder before. What operating system is this?

**Comment by kcbhamu** [comment]
Dear Jackson,
I am using ubuntu20.04.
Yes, there is a ~/.local/bin dir but I do not find any sumo dir or script in ~/.local/bin.

On an anaconda environment using "sudo pip install sumo"  (without sudo I am getting errors)
I am getting this:
Requirement already satisfied: sumo in /root/.local/lib/python2.7/site-packages
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from sumo)
Requirement already satisfied: spglib in /usr/local/lib/python2.7/dist-packages/spglib-1.15.1-py2.7-linux-x86_64.egg (from sumo)
Requirement already satisfied: matplotlib in /home/kcbhamu/.local/lib/python2.7/site-packages (from sumo)
Requirement already satisfied: phonopy>=2.1.3 in /home/kcbhamu/software/phonopy/phonopy (from sumo)
Requirement already satisfied: h5py in /home/kcbhamu/.local/lib/python2.7/site-packages (from sumo)
Requirement already satisfied: scipy in /home/kcbhamu/.local/lib/python2.7/site-packages (from sumo)
Requirement already satisfied: seekpath in /root/.local/lib/python2.7/site-packages (from sumo)
Requirement already satisfied: cycler>=0.10 in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: backports.functools-lru-cache in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: subprocess32 in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: pytz in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: six>=1.10 in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: python-dateutil>=2.1 in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/kcbhamu/.local/lib/python2.7/site-packages (from matplotlib->sumo)
Requirement already satisfied: PyYAML in /home/kcbhamu/.local/lib/python2.7/site-packages (from phonopy>=2.1.3->sumo)
Requirement already satisfied: future>=0.15 in /root/.local/lib/python2.7/site-packages (from seekpath->sumo)
Requirement already satisfied: setuptools in /home/kcbhamu/.local/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib->sumo)

**Comment by kcbhamu** [comment]
With simple pip install in anaconda environment, I am getting below error:

pip install sumo
Collecting sumo
  Using cached sumo-2.2.5-py3-none-any.whl (120 kB)
Requirement already satisfied: numpy in /home/kcbhamu/anaconda3/envs/test_environment/lib/python3.6/site-packages (from sumo) (1.19.5)
Requirement already satisfied: matplotlib in /home/kcbhamu/anaconda3/envs/test_environment/lib/python3.6/site-packages (from sumo) (3.1.3)
Collecting phonopy>=2.1.3
  Using cached phonopy-2.11.0.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pymatgen>=2020.10.20
  Using cached pymatgen-2021.3.3.tar.gz (3.0 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/kcbhamu/anaconda3/envs/test_environment/bin/python /home/kcbhamu/anaconda3/envs/test_environment/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-j1_zgvgf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy>=1.20.1' 'setuptools>=43.0.0'
       cwd: None
  Complete output (2 lines):
  ERROR: Could not find a version that satisfies the requirement numpy>=1.20.1 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
  ERROR: No matching distribution found for numpy>=1.20.1
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/kcbhamu/anaconda3/envs/test_environment/bin/python /home/kcbhamu/anaconda3/envs/test_environment/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-j1_zgvgf/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy>=1.20.1' 'setuptools>=43.0.0' Check the logs for full command output.

**Comment by ajjackson** [comment]
I guess using `sudo` with `--user` would explain the `/root/.local`. I don't recommend ever doing that; those options have opposite purposes.

The numpy version error is strange. I will have a play with an Ubuntu 20 container when I get a chance and see if this can be reproduced.

**Comment by kcbhamu** [comment]
I am sorry for the mistake. The Ubuntu Version is 18.04.5 LTS.

**Comment by kcbhamu** [comment]
I found sumo in ~/.local/bin.
I do not know what was those errors.
Thanks.

**Comment by ajjackson** [comment]
Glad you got it working! It is annoying that some installers will put things there without mentioning that it is not on PATH.
