### ISSUE TITLE
high symmetry k-path symbols are not on the band structure plot with HSE calculations

### ISSUE THREAD

**Issue by kcbhamu** [SMTG-UCL/sumo#145]
Hii, 
I got a nice band structure plot wht sumo.
But when I plot the band structure with HSE-06,
I do not found the k-poins labeling on X-axis.
The message I am getting is

/home/user/.local/bin/sumo-bandplot
Label positions:

It means, for HSE, sumo uses a different file. Right?

How should I supply to the sumo-bandplot so that I get the labeling for k-points of the x-axis?

~

**Comment by ajjackson** [comment]
There is nothing special about using HSE, except that hybrid DFT calcualations benefit more from the split/combine workflow (to avoid long walltimes).

This message means that the symbols are not present in the KPOINTS file. Either you did not generate the file with _kgen_, or _bandplot_ is now seeing a different KPOINTS file.

What KPOINTS file(s) did you use for the calculation?

**Comment by kcbhamu** [comment]
Thanks Jackson,
Here is my detailed response:

case-1: I used the below KPOINTS file (appendix-1) for the calculations and tried to plot the band structure but I did not get the label. Obviously, it does not have the labels, so sumo is not producing the label.

case-2: Alternatively, for the post-processing to plot band structure using sumo, I used the KPOINTS file (Annexure-2) but still I am not getting the labels.

case-3: For the post-processing, I generated the KPOINTS file (copied KPOINTS_band, generated bu sumo-kgen, to KPOINTS) (annexure-3) using sumo-kgen and also with {sumo-kgen --labels "\Gamma,X,M,\Gamma"}, I got Gamma-M-Gamma path while the actual path, I need is Gamma-X-M-Gamma.


Annexure-1

0.040   5   5   1    6  0.040   49    3   14   14   21           # Parameters to Generate KPOINTS (don't Edit This Line)
    55
Reciprocal lattice
    0.00000000000000    0.00000000000000    0.00000000000000     1
    0.20000000000000    0.00000000000000    0.00000000000000     4
    0.40000000000000    0.00000000000000    0.00000000000000     4
    0.20000000000000    0.20000000000000    0.00000000000000     4
    0.40000000000000    0.20000000000000    0.00000000000000     8
    0.40000000000000    0.40000000000000    0.00000000000000     4
    0.00000000000000    0.00000000000000    0.00000000000000     0
    0.03846153846154    0.00000000000000    0.00000000000000     0
    0.07692307692308    0.00000000000000    0.00000000000000     0
    0.11538461538462    0.00000000000000    0.00000000000000     0
    0.15384615384615    0.00000000000000    0.00000000000000     0
    0.19230769230769    0.00000000000000    0.00000000000000     0
    0.23076923076923    0.00000000000000    0.00000000000000     0
    0.26923076923077    0.00000000000000    0.00000000000000     0
    0.30769230769231    0.00000000000000    0.00000000000000     0
    0.34615384615385    0.00000000000000    0.00000000000000     0
    0.38461538461538    0.00000000000000    0.00000000000000     0
    0.42307692307692    0.00000000000000    0.00000000000000     0
    0.46153846153846    0.00000000000000    0.00000000000000     0
    0.50000000000000    0.00000000000000    0.00000000000000     0
    0.50000000000000    0.00000000000000    0.00000000000000     0
    0.50000000000000    0.03846153846154    0.00000000000000     0
    0.50000000000000    0.07692307692308    0.00000000000000     0
    0.50000000000000    0.11538461538462    0.00000000000000     0
    0.50000000000000    0.15384615384615    0.00000000000000     0
    0.50000000000000    0.19230769230769    0.00000000000000     0
    0.50000000000000    0.23076923076923    0.00000000000000     0
    0.50000000000000    0.26923076923077    0.00000000000000     0
    0.50000000000000    0.30769230769231    0.00000000000000     0
    0.50000000000000    0.34615384615385    0.00000000000000     0
    0.50000000000000    0.38461538461538    0.00000000000000     0
    0.50000000000000    0.42307692307692    0.00000000000000     0
    0.50000000000000    0.46153846153846    0.00000000000000     0
    0.50000000000000    0.50000000000000    0.00000000000000     0
    0.50000000000000    0.50000000000000    0.00000000000000     0
    0.47500000000000    0.47500000000000    0.00000000000000     0
    0.45000000000000    0.45000000000000    0.00000000000000     0
    0.42500000000000    0.42500000000000    0.00000000000000     0
    0.40000000000000    0.40000000000000    0.00000000000000     0
    0.37500000000000    0.37500000000000    0.00000000000000     0
    0.35000000000000    0.35000000000000    0.00000000000000     0
    0.32500000000000    0.32500000000000    0.00000000000000     0
    0.30000000000000    0.30000000000000    0.00000000000000     0
    0.27500000000000    0.27500000000000    0.00000000000000     0
    0.25000000000000    0.25000000000000    0.00000000000000     0
    0.22500000000000    0.22500000000000    0.00000000000000     0
    0.20000000000000    0.20000000000000    0.00000000000000     0
    0.17500000000000    0.17500000000000    0.00000000000000     0
    0.15000000000000    0.15000000000000    0.00000000000000     0
    0.12500000000000    0.12500000000000    0.00000000000000     0
    0.10000000000000    0.10000000000000    0.00000000000000     0
    0.07500000000000    0.07500000000000    0.00000000000000     0
    0.05000000000000    0.05000000000000    0.00000000000000     0
    0.02500000000000    0.02500000000000    0.00000000000000     0
    0.00000000000000    0.00000000000000    0.00000000000000     0


Annexure-2

K-Path Generated by VASPKIT.
   10
Line-Mode
Reciprocal
   0.0000000000   0.0000000000   0.0000000000     GAMMA          
   0.5000000000   0.0000000000   0.0000000000     X              
 
   0.5000000000   0.0000000000   0.0000000000     X              
   0.5000000000   0.5000000000   0.0000000000     M              
 
   0.5000000000   0.5000000000   0.0000000000     M              
   0.0000000000   0.0000000000   0.0000000000     GAMMA        

Annexure-3

\Gamma -> X -> M -> \Gamma -> Z -> R -> A -> Z
257
Reciprocal
0.0 0.0 0.0 1 \Gamma
0.0 0.013888888888888888 0.0 1 
0.0 0.027777777777777776 0.0 1 
0.0 0.041666666666666664 0.0 1 
0.0 0.05555555555555555 0.0 1 
0.0 0.06944444444444443 0.0 1 
0.0 0.08333333333333333 0.0 1 
0.0 0.09722222222222222 0.0 1 
0.0 0.1111111111111111 0.0 1 
0.0 0.12499999999999999 0.0 1 
0.0 0.13888888888888887 0.0 1 
0.0 0.1527777777777778 0.0 1 
0.0 0.16666666666666666 0.0 1 
0.0 0.18055555555555552 0.0 1 
0.0 0.19444444444444445 0.0 1 
0.0 0.20833333333333334 0.0 1 
0.0 0.2222222222222222 0.0 1 
0.0 0.2361111111111111 0.0 1 
0.0 0.24999999999999997 0.0 1 
0.0 0.2638888888888889 0.0 1 
0.0 0.27777777777777773 0.0 1 
0.0 0.2916666666666667 0.0 1 
0.0 0.3055555555555556 0.0 1 
0.0 0.3194444444444444 0.0 1 
0.0 0.3333333333333333 0.0 1 
0.0 0.3472222222222222 0.0 1 
0.0 0.36111111111111105 0.0 1 
0.0 0.375 0.0 1 
0.0 0.3888888888888889 0.0 1 
0.0 0.4027777777777778 0.0 1 
0.0 0.4166666666666667 0.0 1 
0.0 0.4305555555555555 0.0 1 
0.0 0.4444444444444444 0.0 1 
0.0 0.4583333333333333 0.0 1 
0.0 0.4722222222222222 0.0 1 
0.0 0.4861111111111111 0.0 1 
0.0 0.49999999999999994 0.0 1 X
0.013888888888888888 0.49999999999999994 0.0 1 
0.027777777777777776 0.49999999999999994 0.0 1 
0.041666666666666664 0.49999999999999994 0.0 1 
0.05555555555555555 0.49999999999999994 0.0 1 
0.06944444444444443 0.49999999999999994 0.0 1 
0.08333333333333333 0.49999999999999994 0.0 1 
0.09722222222222222 0.49999999999999994 0.0 1 
0.1111111111111111 0.49999999999999994 0.0 1 
0.12499999999999999 0.49999999999999994 0.0 1 
0.13888888888888887 0.49999999999999994 0.0 1 
0.1527777777777778 0.49999999999999994 0.0 1 
0.16666666666666666 0.49999999999999994 0.0 1 
0.18055555555555552 0.49999999999999994 0.0 1 
0.19444444444444445 0.49999999999999994 0.0 1 
0.20833333333333334 0.49999999999999994 0.0 1 
0.2222222222222222 0.49999999999999994 0.0 1 
0.2361111111111111 0.49999999999999994 0.0 1 
0.24999999999999997 0.49999999999999994 0.0 1 
0.2638888888888889 0.49999999999999994 0.0 1 
0.27777777777777773 0.49999999999999994 0.0 1 
0.2916666666666667 0.49999999999999994 0.0 1 
0.3055555555555556 0.49999999999999994 0.0 1 
0.3194444444444444 0.49999999999999994 0.0 1 
0.3333333333333333 0.49999999999999994 0.0 1 
0.3472222222222222 0.49999999999999994 0.0 1 
0.36111111111111105 0.49999999999999994 0.0 1 
0.375 0.49999999999999994 0.0 1 
0.3888888888888889 0.49999999999999994 0.0 1 
0.4027777777777778 0.49999999999999994 0.0 1 
0.4166666666666667 0.49999999999999994 0.0 1 
0.4305555555555555 0.49999999999999994 0.0 1 
0.4444444444444444 0.49999999999999994 0.0 1 
0.4583333333333333 0.49999999999999994 0.0 1 
0.4722222222222222 0.49999999999999994 0.0 1 
0.4861111111111111 0.49999999999999994 0.0 1 
0.49999999999999994 0.49999999999999994 0.0 1 M
0.49019607843137253 0.49019607843137253 0.0 1 
0.48039215686274506 0.48039215686274506 0.0 1 
0.47058823529411764 0.47058823529411764 0.0 1 
0.46078431372549017 0.46078431372549017 0.0 1 
0.45098039215686275 0.45098039215686275 0.0 1 
0.4411764705882353 0.4411764705882353 0.0 1 
0.4313725490196078 0.4313725490196078 0.0 1 
0.4215686274509804 0.4215686274509804 0.0 1 
0.4117647058823529 0.4117647058823529 0.0 1 
0.4019607843137255 0.4019607843137255 0.0 1 
0.39215686274509803 0.39215686274509803 0.0 1 
0.38235294117647056 0.38235294117647056 0.0 1 
0.37254901960784315 0.37254901960784315 0.0 1 
0.3627450980392156 0.3627450980392156 0.0 1 
0.35294117647058826 0.35294117647058826 0.0 1 
0.3431372549019608 0.3431372549019608 0.0 1 
0.33333333333333337 0.33333333333333337 0.0 1 
0.32352941176470584 0.32352941176470584 0.0 1 
0.3137254901960784 0.3137254901960784 0.0 1 
0.303921568627451 0.303921568627451 0.0 1 
0.29411764705882354 0.29411764705882354 0.0 1 
0.28431372549019607 0.28431372549019607 0.0 1 
0.2745098039215686 0.2745098039215686 0.0 1 
0.2647058823529412 0.2647058823529412 0.0 1 
0.2549019607843137 0.2549019607843137 0.0 1 
0.24509803921568626 0.24509803921568626 0.0 1 
0.23529411764705882 0.23529411764705882 0.0 1 
0.22549019607843132 0.22549019607843132 0.0 1 
0.2156862745098039 0.2156862745098039 0.0 1 
0.20588235294117646 0.20588235294117646 0.0 1 
0.19607843137254902 0.19607843137254902 0.0 1 
0.18627450980392157 0.18627450980392157 0.0 1 
0.17647058823529407 0.17647058823529407 0.0 1 
0.16666666666666669 0.16666666666666669 0.0 1 
0.1568627450980392 0.1568627450980392 0.0 1 
0.14705882352941174 0.14705882352941174 0.0 1 
0.13725490196078433 0.13725490196078433 0.0 1 
0.12745098039215683 0.12745098039215683 0.0 1 
0.11764705882352942 0.11764705882352942 0.0 1 
0.10784313725490198 0.10784313725490198 0.0 1 
0.09803921568627448 0.09803921568627448 0.0 1 
0.08823529411764708 0.08823529411764708 0.0 1 
0.07843137254901959 0.07843137254901959 0.0 1 
0.06862745098039214 0.06862745098039214 0.0 1 
0.05882352941176469 0.05882352941176469 0.0 1 
0.04901960784313724 0.04901960784313724 0.0 1 
0.039215686274509796 0.039215686274509796 0.0 1 
0.029411764705882346 0.029411764705882346 0.0 1 
0.019607843137254898 0.019607843137254898 0.0 1 
0.009803921568627449 0.009803921568627449 0.0 1 
0.0 0.0 0.0 1 \Gamma
0.0 0.0 0.05000000000000001 1 
0.0 0.0 0.10000000000000002 1 
0.0 0.0 0.15 1 
0.0 0.0 0.20000000000000004 1 
0.0 0.0 0.25 1 
0.0 0.0 0.3 1 
0.0 0.0 0.35 1 
0.0 0.0 0.4000000000000001 1 
0.0 0.0 0.45000000000000007 1 
0.0 0.0 0.5 1 Z
0.0 0.013888888888888888 0.5 1 
0.0 0.027777777777777776 0.5 1 
0.0 0.041666666666666664 0.5 1 
0.0 0.05555555555555555 0.5 1 
0.0 0.06944444444444443 0.5 1 
0.0 0.08333333333333333 0.5 1 
0.0 0.09722222222222222 0.5 1 
0.0 0.1111111111111111 0.5 1 
0.0 0.12499999999999999 0.5 1 
0.0 0.13888888888888887 0.5 1 
0.0 0.1527777777777778 0.5 1 
0.0 0.16666666666666666 0.5 1 
0.0 0.18055555555555552 0.5 1 
0.0 0.19444444444444445 0.5 1 
0.0 0.20833333333333334 0.5 1 
0.0 0.2222222222222222 0.5 1 
0.0 0.2361111111111111 0.5 1 
0.0 0.24999999999999997 0.5 1 
0.0 0.2638888888888889 0.5 1 
0.0 0.27777777777777773 0.5 1 
0.0 0.2916666666666667 0.5 1 
0.0 0.3055555555555556 0.5 1 
0.0 0.3194444444444444 0.5 1 
0.0 0.3333333333333333 0.5 1 
0.0 0.3472222222222222 0.5 1 
0.0 0.36111111111111105 0.5 1 
0.0 0.375 0.5 1 
0.0 0.3888888888888889 0.5 1 
0.0 0.4027777777777778 0.5 1 
0.0 0.4166666666666667 0.5 1 
0.0 0.4305555555555555 0.5 1 
0.0 0.4444444444444444 0.5 1 
0.0 0.4583333333333333 0.5 1 
0.0 0.4722222222222222 0.5 1 
0.0 0.4861111111111111 0.5 1 
0.0 0.49999999999999994 0.5 1 R
0.013888888888888888 0.49999999999999994 0.5 1 
0.027777777777777776 0.49999999999999994 0.5 1 
0.041666666666666664 0.49999999999999994 0.5 1 
0.05555555555555555 0.49999999999999994 0.5 1 
0.06944444444444443 0.49999999999999994 0.5 1 
0.08333333333333333 0.49999999999999994 0.5 1 
0.09722222222222222 0.49999999999999994 0.5 1 
0.1111111111111111 0.49999999999999994 0.5 1 
0.12499999999999999 0.49999999999999994 0.5 1 
0.13888888888888887 0.49999999999999994 0.5 1 
0.1527777777777778 0.49999999999999994 0.5 1 
0.16666666666666666 0.49999999999999994 0.5 1 
0.18055555555555552 0.49999999999999994 0.5 1 
0.19444444444444445 0.49999999999999994 0.5 1 
0.20833333333333334 0.49999999999999994 0.5 1 
0.2222222222222222 0.49999999999999994 0.5 1 
0.2361111111111111 0.49999999999999994 0.5 1 
0.24999999999999997 0.49999999999999994 0.5 1 
0.2638888888888889 0.49999999999999994 0.5 1 
0.27777777777777773 0.49999999999999994 0.5 1 
0.2916666666666667 0.49999999999999994 0.5 1 
0.3055555555555556 0.49999999999999994 0.5 1 
0.3194444444444444 0.49999999999999994 0.5 1 
0.3333333333333333 0.49999999999999994 0.5 1 
0.3472222222222222 0.49999999999999994 0.5 1 
0.36111111111111105 0.49999999999999994 0.5 1 
0.375 0.49999999999999994 0.5 1 
0.3888888888888889 0.49999999999999994 0.5 1 
0.4027777777777778 0.49999999999999994 0.5 1 
0.4166666666666667 0.49999999999999994 0.5 1 
0.4305555555555555 0.49999999999999994 0.5 1 
0.4444444444444444 0.49999999999999994 0.5 1 
0.4583333333333333 0.49999999999999994 0.5 1 
0.4722222222222222 0.49999999999999994 0.5 1 
0.4861111111111111 0.49999999999999994 0.5 1 
0.49999999999999994 0.49999999999999994 0.5 1 A
0.49019607843137253 0.49019607843137253 0.5 1 
0.48039215686274506 0.48039215686274506 0.5 1 
0.47058823529411764 0.47058823529411764 0.5 1 
0.46078431372549017 0.46078431372549017 0.5 1 
0.45098039215686275 0.45098039215686275 0.5 1 
0.4411764705882353 0.4411764705882353 0.5 1 
0.4313725490196078 0.4313725490196078 0.5 1 
0.4215686274509804 0.4215686274509804 0.5 1 
0.4117647058823529 0.4117647058823529 0.5 1 
0.4019607843137255 0.4019607843137255 0.5 1 
0.39215686274509803 0.39215686274509803 0.5 1 
0.38235294117647056 0.38235294117647056 0.5 1 
0.37254901960784315 0.37254901960784315 0.5 1 
0.3627450980392156 0.3627450980392156 0.5 1 
0.35294117647058826 0.35294117647058826 0.5 1 
0.3431372549019608 0.3431372549019608 0.5 1 
0.33333333333333337 0.33333333333333337 0.5 1 
0.32352941176470584 0.32352941176470584 0.5 1 
0.3137254901960784 0.3137254901960784 0.5 1 
0.303921568627451 0.303921568627451 0.5 1 
0.29411764705882354 0.29411764705882354 0.5 1 
0.28431372549019607 0.28431372549019607 0.5 1 
0.2745098039215686 0.2745098039215686 0.5 1 
0.2647058823529412 0.2647058823529412 0.5 1 
0.2549019607843137 0.2549019607843137 0.5 1 
0.24509803921568626 0.24509803921568626 0.5 1 
0.23529411764705882 0.23529411764705882 0.5 1 
0.22549019607843132 0.22549019607843132 0.5 1 
0.2156862745098039 0.2156862745098039 0.5 1 
0.20588235294117646 0.20588235294117646 0.5 1 
0.19607843137254902 0.19607843137254902 0.5 1 
0.18627450980392157 0.18627450980392157 0.5 1 
0.17647058823529407 0.17647058823529407 0.5 1 
0.16666666666666669 0.16666666666666669 0.5 1 
0.1568627450980392 0.1568627450980392 0.5 1 
0.14705882352941174 0.14705882352941174 0.5 1 
0.13725490196078433 0.13725490196078433 0.5 1 
0.12745098039215683 0.12745098039215683 0.5 1 
0.11764705882352942 0.11764705882352942 0.5 1 
0.10784313725490198 0.10784313725490198 0.5 1 
0.09803921568627448 0.09803921568627448 0.5 1 
0.08823529411764708 0.08823529411764708 0.5 1 
0.07843137254901959 0.07843137254901959 0.5 1 
0.06862745098039214 0.06862745098039214 0.5 1 
0.05882352941176469 0.05882352941176469 0.5 1 
0.04901960784313724 0.04901960784313724 0.5 1 
0.039215686274509796 0.039215686274509796 0.5 1 
0.029411764705882346 0.029411764705882346 0.5 1 
0.019607843137254898 0.019607843137254898 0.5 1 
0.009803921568627449 0.009803921568627449 0.5 1 
0.0 0.0 0.5 1 Z

**Comment by ajjackson** [comment]
The KPOINTS file for plotting needs to have the same points/weights as the KPOINTS for the calculation.

You might be able to get the first file to work if you add the labels in the right places. I don't expect the second file to work because it is Line-mode (which doesn't sample appropriate spacing) and lacks the zero-weighted k-points. The third file is also missing the zero-weighted k-points (and contains more points than the calculation).

**Comment by ajjackson** [comment]
@kcbhamu did you manage to get a consistent set of files and plot in the end?

**Comment by kcbhamu** [comment]
Dear Jackson

No, I couldn't.
I put on hold my project. I will see it later.

**Comment by kcbhamu** [comment]
1st approach worked provided that we give symmetric points in front of the appropriate ROW.
Example: 
by default we have 0.00 0.00 0.00   0.0  for Gamma     # in  zero-weighted k-points
so 0.00 0.00 0.00  0.0  Gamma will work.
