### ISSUE TITLE
How can I change the font style to Times New Roman

### ISSUE THREAD

**Issue by kcbhamu** [SMTG-UCL/sumo#146]
Hi,
How can I change the font style to the Times New Roman in sumo?

Thanks

**Comment by ajjackson** [comment]
All the Sumo plotting tools have a `--font` option. In principle, using your favourite font is as simple as, e.g. `--font='Times New Roman'`.

In practice, the font name will be passed to Matplotlib. It is not always very obvious what name Matplotlib is looking for, and not all font formats are accepted (I think it needs to be TTF or OTF). Please look for information on how to use Times New Roman with Matplotlib for your operating system. (On Linux it is probably necessary to install the MS core fonts and refresh Matplotlib's cache.) You should then be able to pass the appropriate name as e.g. `--font='Times New Roman'`.

If you get the error message `findfont: Font family ['sans-serif'] not found. Falling back to ...` this means that the font name was not recognised. (It isn't really anything to do with being sans-serif, that's just the family we temporarily put user-requested fonts into.)

On my system I find "Nimbus Roman" is an acceptable substitute.

**Comment by kcbhamu** [comment]
Dear Jackson,
I have tried all these but I could not get sucess.
Is there anyway to update the matplotlib in such a way that it import the Times New Roman (TNR) font when we execute sumo-bandplot?
I am sure, every user will face this issue who wish to use TNR.

**Comment by kcbhamu** [comment]
Dear Jackson,
I have tried all these but I could not get success.
Is there anyway to update the matplotlib in such a way that it imports the Times New Roman (TNR) font when we execute sumo-bandplot?
I am sure, every user will face this issue who wish to use TNR.

**Comment by ajjackson** [comment]
Improving Matplotlib's font manager is way out of scope for this project, I'm afraid. Perhaps if you raise it with Matplotlib they can point you to more resources? https://github.com/matplotlib/matplotlib

**Comment by utf** [comment]
If you are on linux, this is a recipe I use all the time for getting custom fonts to work.

1. Make the `~/.fonts` directory if it doesn't already exist.
2. Copy your custom font into the `~/.fonts` directory.
3. Run `rm -rf ~/.cache`.
4. Run sumo with `--font "Times New Roman`.

**Comment by kcbhamu** [comment]
Interesting,
My font file name is "Times_New_Romance.ttf" and I kept it in the ~/.fonts directory.
and then run the sumo with --font "Times New Roman". But still, I am getting the default fonts with the warning "findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans."
Could you please send me your font file?
Thanks

**Comment by utf** [comment]
It doesn't say anything about the font name in the part you pasted. Can you please paste the full error message here?

Also, did you definitely run `rm -rf ~/.cache`?

**Comment by kcbhamu** [comment]
Yes, I did that. I am always getting below message and the fonts are in default settings not in Times New Roman. 

findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans

**Comment by utf** [comment]
Strange, normally the error is something like:
```
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
findfont: Generic family 'sans-serif' not found because none of the following families were found: Times New Roman
```

Can you paste the full sumo command you are running.

I just downloaded the times new roman font file from this page: https://www.fontmirror.com/times-new-roman And the steps above worked for me.

**Comment by kcbhamu** [comment]
sumo-bandplot --font "Times New Roman"

**Comment by utf** [comment]
Ok, I just tested your command on my system using the steps I outlined above and it worked fine. I'm afraid if it is still not working there must be an issue with your matplotlib installation/configuration.

**Comment by utf** [comment]
Are you sure you have installed Times New Roman? Your font name is `"Times_New_Romance.ttf"` which is a different font: https://www.dafont.com/times-new-romance.font

**Comment by kcbhamu** [comment]
I tried to install it but couldn't get success. Then I only found this file on Google and kept it in the ~/.fonts

**Comment by utf** [comment]
Did you try using this font? https://www.fontmirror.com/times-new-roman

**Comment by kcbhamu** [comment]
Thank you very much. 
I will check it and update you. May be tomorrow as I left the office few minutes ago (its 2am) and I don't have the laptop with me.
Thanks for your all help.

**Comment by kcbhamu** [comment]
Thank you So much. It worked for me.
