### ISSUE TITLE
[BUG] dosplot does not shift to zero

### ISSUE THREAD

**Issue by pzarabadip** [SMTG-UCL/sumo#153]
Hi,
I just noticed that `sumo-dosplot` does not pass the `--no-shift` argument to the `plotter` in `dos_plot` function.
Although `dos_plot` has the the `shift` argument here:
https://github.com/SMTG-UCL/sumo/blob/c6b4bf85aafd537601a679334848941089bbf540/sumo/cli/dosplot.py#L53

It does not pass anything to `plotter` here:
https://github.com/SMTG-UCL/sumo/blob/c6b4bf85aafd537601a679334848941089bbf540/sumo/cli/dosplot.py#L304-L326

So, it is always `True`. I could confirm it by adding `zero_to_efermi=shift` argument to the `plotter`.

If you would like, I can open a PR to address this issue.

Cheers,
Pezhman

**Comment by bugaboo** [comment]
Can confirm both the bug and the solution of adding `zero_to_efermi=shift`.

**Comment by ajjackson** [comment]
Thanks both for report and confirmation. @utf this seems like a straightforward fix, are there any subtleties we should be watching out for?

**Comment by pzarabadip** [comment]
Thanks all for comments. I just opened a PR with fix.
Cheers,
Pezhman
