### ISSUE TITLE
Bandplot is ignoring one of my labels

### ISSUE THREAD

**Issue by R-applet** [SMTG-UCL/sumo#155]
Hello,

I am using sumo-bandplot to plot the bandstructure and for some reason one of my labels are not being used along the x-axis. I tried using sumo-kgen to make sure the path was correct and it still ignores a label. I have attached the KPOINTS file I used to run the calculation (KPOINTS_calc.txt) as well as the KPOINTS file I generated from sumo-kgen (KPOINTS_kgen.txt). 

[KPOINTS_kgen.txt](https://github.com/SMTG-UCL/sumo/files/7553013/KPOINTS_kgen.txt)

[KPOINTS_calc.txt](https://github.com/SMTG-UCL/sumo/files/7553016/KPOINTS_calc.txt)

When I use the KPOINTS file generated by sumo-kgen I get the following:

![image](https://user-images.githubusercontent.com/79952459/142166592-77ff462e-2d92-461b-b5ae-cc533b92d2fd.png)

I have never had this issue in the past and so I am not sure how to fix it. The path should be Gamma --> X --> M --> Gamma, but the plot labels Gamma --> M --> Gamma. 

I hope you can see the files and image I added and can help me figure out what is happening.

Thanks,

Robert Appleton

**Comment by ajjackson** [comment]
Hi Robert,

apologies for slow response and thanks for the report.

This seems strange. Sumo reads the KPOINTS file as a side-effect of reading the vasprun.xml file with Pymatgen. If I try using Pymatgen's importer

```python
from pymatgen.io.vasp.inputs import Kpoints
kp = Kpoints.from_file('KPOINTS_kgen.txt')
print(kp.labels)
```

then all the labels are there. So it could be that something has changed with a particular Pymatgen version, or that Sumo has picked up the wrong KPOINTS file, or that something is going wrong once it tries to parse the data coming back from Pymatgen.

I can't really pick that apart further without the vasprun.xml file. Did you manage to resolve this problem?

**Comment by R-applet** [comment]
Thanks for your response. Honestly, I could not figure out the issue so ended up manually inserting the label. I will note that installing pymatgen on our cluster system is always a bit tricky and it’s possible the version is different? Anyways it was strange but haven't had an issue before this or since.

Robert

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by utf** [comment]
Thanks for the update!
