### ISSUE TITLE
horizontal line in band plot

### ISSUE THREAD

**Issue by linton1995** [SMTG-UCL/sumo#157]
Hey, how can I give a horizontal dotted line at the fermi label in the band plot just like below. is there any tool?

**Comment by ajjackson** [comment]
Hi Linton, I'm working on this long-requested feature in #68 . Hopefully you won't have to wait for this for too much longer!

**Comment by linton1995** [comment]
Thanks sir i am eagerly waiting for it.

**Comment by ajjackson** [comment]
Done! This has not been packaged into a release yet, please follow the README instructions for Developer installation if you wish to access the feature immediately.
