### ISSUE TITLE
a vertical dotted line at the Fermi level (FL) for dos plot and a horizontal line at FL for band  very much needed for explain the electrical conductivity very clearly in a paper

### ISSUE THREAD

**Issue by linton1995** [SMTG-UCL/sumo#159]
![image](https://user-images.githubusercontent.com/80808628/150602569-4361b864-6cc5-4cbc-83a0-4504aa2ef6f9.png)
![image](https://user-images.githubusercontent.com/80808628/150602702-0ea1c8e5-206f-45cf-952b-4bb400c621ee.png)

**Comment by ajjackson** [comment]
This feature has just been implemented and is available from the Master branch of Sumo. Use the `--zero-line` argument to enable the dashed line at the reference energy. If you need to shift the reference energy away from the default VBM/EFermi position this can be done with the `--zero-energy` argument.

I am glad to hear this will be useful for your research!
