### ISSUE TITLE
How to plot band structure with spin polarised + spin orbit coupling band structre

### ISSUE THREAD

**Issue by neerukulhari** [SMTG-UCL/sumo#161]
I am not able to plot band structure with SOC.
Every time I do they show this error.

/home/neeraj/.local/lib/python3.8/site-packages/pymatgen/core/__init__.py:49: UserWarning: Error loading .pmgrc.yaml: [Errno 2] No such file or directory: '/home/neeraj/.pmgrc.yaml'. You may need to reconfigure your yaml file.
  warnings.warn(f"Error loading .pmgrc.yaml: {ex}. You may need to reconfigure your yaml file.")
Traceback (most recent call last):
  File "/home/neeraj/.local/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/home/neeraj/.local/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 462, in main
    bandplot(filenames=args.filenames, prefix=args.prefix,
  File "/home/neeraj/.local/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 246, in bandplot
    plt = plotter.get_plot(zero_to_efermi=True, ymin=ymin, ymax=ymax,
  File "/home/neeraj/.local/lib/python3.8/site-packages/sumo/plotting/bs_plotter.py", line 136, in get_plot
    if self._bs.is_spin_polarized or self._bs.is_metal():
AttributeError: 'list' object has no attribute 'is_spin_polarized'

**Comment by utf** [comment]
Hi, please can you try updating sumo and pymatgen to the latest versions.

**Comment by neerukulhari** [comment]
Yes I have updated.
Is it possible to plot non collinear spin polarised plots?
If yes what are the commands.
Thankyou

**Comment by utf** [comment]
Yes it should work fine.

I don't think you are using the latest version of sumo. Your error says line 136 of `/home/neeraj/.local/lib/python3.8/site-packages/sumo/plotting/bs_plotter.py` contains:
```
if self._bs.is_spin_polarized or self._bs.is_metal():
```
But in the latest version it is different: https://github.com/SMTG-UCL/sumo/blob/732a10f30817c48a36be493effba9a07a7c829aa/sumo/plotting/bs_plotter.py#L136

I'm fairly certain this is an issue we fixed in the latest version. Please double check you have updated properly.

**Comment by neerukulhari** [comment]
I checked my bs_plotter.py with the file you provided in the above link and both the files are exactly same.
I am attaching my vasprun.xml file for spin polarised SOC.
Have a look
https://we.tl/t-DNAjLqu8Y3

Thanks

**Comment by utf** [comment]
Your vasprun plotted fine for me. Please double check your installation, as the error message shows that you don't have the right version installed. 

If you can't get it to work, I suggest you install conda and create a fresh conda environment.

**Comment by neerukulhari** [comment]
I have done both things. Can you share what plot you are getting. Because I am also getting one plot. But  I cannot differentiate neither spinors nor spin states.

**Comment by utf** [comment]
I don't have the your kpoints file so there are no k-points labels but this is the plot I get

Note that with SOC enabled there is no-longer a clean distinction between spin-up and spin-down bands. If you check the OUTCAR you will see there is only a single set of bands. If you plot manually you can project the spin-polarisation onto the band structure with a colour/fatbands, however this has not been implemented in sumo.

<img width="710" alt="Screenshot 2022-03-10 at 14 59 56" src="https://user-images.githubusercontent.com/1330638/157689156-ec09c9ba-f84b-44a0-ba00-06292c73f74c.png">

**Comment by neerukulhari** [comment]
Thanks, this is what I was getting.
That's what I was asking, it's not possible to project spinors here.
Thanks for your time.
