### ISSUE TITLE
scissor options does not apply to DOS plot when plotting band and DOS together

### ISSUE THREAD

**Issue by akentphonon** [SMTG-UCL/sumo#164]
Dear developers,

Thank you for this great tool - I am using sumo-bandplot to plot vasp output files, and applying the scissor options to fit the experimental bandgap. 

when I run a command like:

`sumo-bandplot --scissor 1.26132 --ymin -2 --ymax 4 --band-edges  --dos vasprun.xml'

This only shifts the band structure but not the DOS.

Any thoughts will be helpful.

Thanks!!!
AK

**Comment by utf** [comment]
Thanks for the bug report. This should be fixed in sumo version 2.3.0.
