### ISSUE TITLE
sumo-kgen

### ISSUE THREAD

**Issue by isabelmoib** [SMTG-UCL/sumo#168]
Hi,

If I use sumo-kgen for orthorhombic cell only with substitute one atom by a dopant atom, sumo reads lattice type as monoclinic.

Still can we use the suggested path?

Best regards,
Ibra

**Comment by ajjackson** [comment]
That's interesting, there are few things that could be happening. What spacegroup does it report, and what spacegroup were you expecting?

One possibility is that your lattice vectors are not quite orthorhombic (e.g. following relaxation). Another possibility is that spglib detected a higher-symmetry monoclinic system within your orthorhombic cell.

**Comment by isabelmoib** [comment]
I was expecting space group 62, same as the pristine structure (62), however I got space group 6.

The lattice parameters are same as the pristine structure. So, exactly spglib detected the monoclinic symmetry within the orthorhombic.
So, is it OK to use the suggested path by Sumo in that case?

**Comment by ajjackson** [comment]
It is a bit unintuitive that you can get from an orthorhombic to a "monoclinic" space group without distorting the lattice vectors. I think the key point is that spacegroup 6 (_P1m1_) has only one symmetry operation: a mirror plane. I guess the lattice angles don't really matter if you break all the other symmetry? If the only symmetry is a mirror plane it has to be _P1m1_. A second mirror plane could get you into the orthorhombic _Pmm2_.

**Comment by utf** [comment]
Yes, α = β = γ = 90° does not mean the crystal is orthorhombic. But for a crystal to be orthorhombic the conventional cell must have α = β = γ = 90°. They are not the same thing.
