### ISSUE TITLE
Support castepxbin >= 0.1

### ISSUE THREAD

**Issue by onny** [SMTG-UCL/sumo#173]
Hey,
currently we have to patch the sumo package on NixOS to support castepxbin versions >= 0.1. The tests work fine but sumo pins castepxbin version to 0.1.
Can this dependency be updated or loosen?

Best regards
Jonas

**Comment by ajjackson** [comment]
No reason that I know of. There has only been one more version since then so we could change the requirement to `<1.0` if we trust the project to version responsibly!

**Comment by utf** [comment]
Ok, I fixed this and pushed a new version (2.3.4) with the changes.

**Comment by onny** [comment]
Thanks, already created a PR for the nixpkgs package

**Comment by utf** [comment]
Updated!
