### ISSUE TITLE
Is it possible to turn off different coloring for valence/conduction bands?

### ISSUE THREAD

**Issue by alpinnovianus** [SMTG-UCL/sumo#174]
When plotting band structure of insulator, the valence and conduction bands are colored differently by default.

Is there a way to turn this color coding off? (so the VB and CB have the same color)

**Comment by ajjackson** [comment]
Hi,

the colour scheme for band structure plots uses the first two colours from the active style.
By default that will be from this style file: https://github.com/SMTG-UCL/sumo/blob/master/sumo/plotting/sumo_bs.mplstyle
but you can provide an alternative style sheet that takes priority: https://smtg-ucl.github.io/sumo/customising-plots.html

So to make both lines blue you could create a stylesheet with
```
axes.prop_cycle : cycler('color', ['3953a4', '3953a4', 'd93b2b', '0db14b', 'f0a3ff', '0075dc', '993f00', '4c005c', '426600', 'ff0010', '9dcc00', 'c20088', '003380', 'ffa405', 'ffff00', 'ff5005', '5ef1f2', '740aff', '990000', '00998f', '005c31', '2bce48', 'ffcc99', '94ffb5', '8f7c00', '6fa8bb', '808080'])
```

(You could remove the other colours and just specify one, but this will cause issues if you try to plot the PDOS as well!)

**Comment by utf** [comment]
Just to add to Adams answer. You can do this by:

1. Making a file called `new_style.mplstyle` containing:
```
axes.prop_cycle : cycler('color', ['3953a4', '3953a4'])
```
2. Running sumo with the new style applied:
```bash
sumo-bandplot --style new_style.mplstyle
```

**Comment by alpinnovianus** [comment]
Thank you for the comments.

On a related note, for the projected bands, how should I change the colours in **mode stacked**?
if the method is the same as above, what is the ordering rule for the color list above?

I have 3 element projections in 1 figure of up-spin only:
sumo-bandplot --spin 1 --ymin -2 --ymax 2 --format "png" --project Cu,Hg --mode stacked --circle-size 90

![image](https://user-images.githubusercontent.com/74560218/188055338-ba3e370b-7e5c-4349-9a1e-ea1956f33a6c.png)

on the subsequent figure, I want to project only to 2 elements, but I want Hg to also be in green color like in the first figure.

![image](https://user-images.githubusercontent.com/74560218/188055459-fac65aa8-e176-44a6-978d-d45bb735753f.png)

I tried the method above, but I was not successful.

**Comment by ajjackson** [comment]
I don't understand what you mean by "the series of custom colours" or "the same method as above"? I think the stacked method follows the style colour series. This is only custom if you want it to be, there are lots of inbuilt pallettes available.

Separate calls to Sumo can't know what colours were assigned to elements in a previous run: that either requires more complicated options to be implemented (remember that it has to also work for different orbital combinations...) or a bit of user style fiddling. (i.e. you can make a style that skips the second colour in order to get the consistent Cu, Hg colours on the second plot.)

**Comment by alpinnovianus** [comment]
Hi Adam,

> I don't understand what you mean by "the series of custom colours" or "the same method as above"? I think the stacked method follows the style colour series. This is only custom if you want it to be, there are lots of inbuilt pallettes available.

I refer to line 627 of bs_plotter.py about the series of custom colours. "the same method as above" simply refer to the sumo-bandplot --style new_style.mplstyle that you and utf suggested, not the colors of a previous run.

![image](https://user-images.githubusercontent.com/74560218/188475468-43926fe7-359f-458d-8571-ccc5dedd474d.png)

If I understand correctly, this line puts a default set of five colours for the stacked mode. Only when more than 5 projections would the program refer to the style color series which in turn we can modify. 

This is why I have been using sumo-bandplot --style new_style.mplstyle to no avail when in stacked mode.
I only succeeded after editing line 627 of bs_plotter.py directly.

Hope this clarifies,

Thanks!
