### ISSUE TITLE
Customising Sumo Plots default sumo style sheet link not working

### ISSUE THREAD

**Issue by andreangletti** [SMTG-UCL/sumo#177]
The link to see examples of what can be tuned, with the default sumo style sheet is not working:
https://github.com/SMTG-UCL/sumo/blob/mpl-style/sumo/plotting/sumo_base.mplstyle

The link is mentioned on the page Customising Sumo Plots:
https://smtg-ucl.github.io/sumo/customising-plots.html

It would be nice to be able check the default sheet so that one can know how to modify the parameters, for the line width for example, and others as well.

Thank you.

**Comment by ajjackson** [comment]
Thanks for highlighting, it's a simple thing to fix :-)
