### ISSUE TITLE
Sumo-bandplot is not showing KPOINTS labels

### ISSUE THREAD

**Issue by jfrmhrz** [SMTG-UCL/sumo#184]
I would like to report this issue for graphs generated with sumo-bandplot. I have a predefined Kpath using sumo-kgen with following arguments:
>> sumo-kgen --kpoints "0 0 0, 0 0.5 0, 0.5 0.5 0, 0 0 0" --labels "\Gamma, X, M, \Gamma"
after getting the KPOINTS file and by using sumo-bandplot, the final plot is not showing any labels in the X-axis @ajjackson 
![band](https://user-images.githubusercontent.com/117495403/200100382-be564c4d-5ec7-49a7-bff4-b832372f83da.png)

**Comment by ajjackson** [comment]
Interesting! If you look in the generated KPOINTS file, are the labels there? They should appear as a fifth column at the relevant points.

**Comment by jfrmhrz** [comment]
It’s been my mistake I used a different KPOINTS file during the calculation. We can close the Issue. 
Thank you :D

**Comment by ajjackson** [comment]
Ok, happy computing!
