### ISSUE TITLE
 Invalid Style Override 'custom.mplstyle'

### ISSUE THREAD

**Issue by jfrmhrz** [SMTG-UCL/sumo#188]
I am trying to override sumo-bandplot style by passing a custom mplstyle file using --style option like that: 

sumo-bandplot --format png --dpi 900 --font Georgia --zero-line --height 5 --width 1.5 --ymax 6 --ymin -6 --prefix total --style custom.mplstyle

However, I am getting the following error into the terminal, and the style file i am passing is being igneord :

QApplication: invalid style override 'custom.mplstyle' passed, ignoring it.
	Available styles: Windows, Fusion

I wonder whether it is a problem in my system or from sum-bandplot?  
Thank you @ajjackson

**Comment by ajjackson** [comment]
I've never seen a message like this before, what OS are you using and how was Sumo installed?

Are you getting a Python traceback that shows which lines cause the error, or does the error message seem to be coming from elsewhere?

**Comment by ajjackson** [comment]
It looks like some kind of external framework has wrapped itself around sumo, intercepted the `--style` argument and is complaining that it isn't what it expected!

**Comment by JaafarMehrez** [comment]
I am on a Debian machine, I have Sumo installed via pip: pip install --user
sumo
There are no other error messages coming from python. I suppose the error
message is coming from elsewhere and it happens to be at the beginning,
probably something related to matplotlib.
I have reinstalled sumo in a conda environment and the error was not there,
so it seems that it has to do with my environment variables.

**Comment by ajjackson** [comment]
Odd stuff! Glad you got things working, will close this for now.
