### ISSUE TITLE
How to control the size of band edges

### ISSUE THREAD

**Issue by kcbhamu** [SMTG-UCL/sumo#192]
How can we control the size of circles predicted using "band-edges" ?

**Comment by ajjackson** [comment]
This is currently hard-coded but does not need to be; I have opened a pull request which would allow the value to be overridden by a user style file with `lines.markersize`.

**Comment by kcbhamu** [comment]
I could not understand it. Should I update sumo?

**Comment by ajjackson** [comment]
First the changes need to be reviewed by another developer; then they will be available in the next Sumo release.

It is possible to try them out before then but if you are not comfortable with Python development then it is probably better to wait.
