### ISSUE TITLE
How to make power of 10 in superscript in optical spectra

### ISSUE THREAD

**Issue by kcbhamu** [SMTG-UCL/sumo#196]
Hello,
I am trying to plot the optical spectra of some material. I am not getting the power in superscript at the y-axis.
I am attahing my plot here.

![absorption](https://user-images.githubusercontent.com/15922639/212633778-c7f3e00b-34c7-4178-a4ad-d16c8d245533.png)

How can I get rid of this?

**Comment by ajjackson** [comment]
That is odd, can you let us know what versions of Numpy and Matplotlib you are using?

**Comment by kcbhamu** [comment]
Numpy= 1.20.2  and 1.22.3
matplotlib=3.4.1 and 3.6.2

**Comment by utf** [comment]
Fixed in #203
