### ISSUE TITLE
How add non-analytical term corrections with sumo command 

### ISSUE THREAD

**Issue by kcbhamu** [SMTG-UCL/sumo#202]
I am plotting the phonon band structure calculated using VASP+Phonopy. I need to add the "non-analytical term corrections".

Without sumo, I can use this command:  phonopy -c POSCAR band.conf   --nac 
Could you please tell me how can add "non-analytical term corrections" with the sumo plotter?

**Comment by utf** [comment]
Please see the instructions here: https://smtg-ucl.github.io/sumo/sumo-phonon-bandplot.html#basic-options

You need the `--born` option.
