### ISSUE TITLE
symprec usage in `sumo-phonon-bandplot`

### ISSUE THREAD

**Issue by badw** [SMTG-UCL/sumo#205]
line 403 in `cli/phonon_bandplot.py` 

in `phonon.load_phonopy(...)`

there is a missing `symprec=symprec` 

which then allows you to use the `symprec` tag when using `sumo-phono-bandplot --symprec 0.01`

**Comment by badw** [comment]
cool I think i managed it!

**Comment by utf** [comment]
Closed in #207
