### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by darnoceloc** [SMTG-UCL/sumo#21]
I'm getting no response from the sudo terminal commands when performing the standard pip installation.
Below is the result of my most recent pip installation attempt.
Is it necessary to build from the source files?

**Requirement already satisfied: sumo in /home/darnoceloc/.local/lib/python3.6/site-packages (1.0.9)
Requirement already satisfied: h5py in /home/darnoceloc/.local/lib/python3.6/site-packages (from sumo) (2.8.0)
Requirement already satisfied: spglib in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from sumo) (1.10.3.65)
Requirement already satisfied: pymatgen>=2017.12.30 in /home/darnoceloc/.local/lib/python3.6/site-packages (from sumo) (2018.6.27)
Requirement already satisfied: scipy in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from sumo) (1.1.0)
Requirement already satisfied: seekpath in /home/darnoceloc/.local/lib/python3.6/site-packages (from sumo) (1.8.1)
Requirement already satisfied: phonopy in /home/darnoceloc/.local/lib/python3.6/site-packages (from sumo) (1.13.2.13)
Requirement already satisfied: numpy in /home/darnoceloc/.local/lib/python3.6/site-packages (from sumo) (1.14.4)
Requirement already satisfied: matplotlib in /home/darnoceloc/.local/lib/python3.6/site-packages (from sumo) (2.2.2)
Requirement already satisfied: six in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from h5py->sumo) (1.11.0)
Requirement already satisfied: monty>=0.9.6 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (1.0.2)
Requirement already satisfied: palettable>=2.1.1 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (3.1.1)
Requirement already satisfied: ruamel.yaml>=0.15.6 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (0.15.42)
Requirement already satisfied: requests in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (2.19.1)
Requirement already satisfied: pandas in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (0.23.2)
Requirement already satisfied: tabulate in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (0.8.2)
Requirement already satisfied: pydispatcher>=2.0.5 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (2.0.5)
Requirement already satisfied: sympy in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from pymatgen>=2017.12.30->sumo) (1.1.1)
Requirement already satisfied: future>=0.15 in /home/darnoceloc/.local/lib/python3.6/site-packages (from seekpath->sumo) (0.16.0)
Requirement already satisfied: PyYAML in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from phonopy->sumo) (3.12)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/darnoceloc/.local/lib/python3.6/site-packages (from matplotlib->sumo) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from matplotlib->sumo) (2.2.0)
Requirement already satisfied: pytz in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from matplotlib->sumo) (2018.5)
Requirement already satisfied: cycler>=0.10 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from matplotlib->sumo) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from matplotlib->sumo) (2.7.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from requests->pymatgen>=2017.12.30->sumo) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from requests->pymatgen>=2017.12.30->sumo) (2.7)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from requests->pymatgen>=2017.12.30->sumo) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from requests->pymatgen>=2017.12.30->sumo) (2018.4.16)
Requirement already satisfied: setuptools in /home/darnoceloc/miniconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->sumo) (39.2.0)**

**Comment by utf** [comment]
Hi @darnoceloc, thanks for using sumo.

When you say no response what do you mean?

Does the command hang and never finish, or does it finish without giving any output?

When you run sumo for the first time, it can take rather a long time for the script to start executing as `pymatgen` is quite bulky. It could be that the script is just loading the dependencies. 

Alternatively, many of the scripts do not produce output on the terminal but instead write files to the current directory. Have any files been written?

**Comment by ajjackson** [comment]
There is no indication of an installation problem in the log provided. Can you give an example of a command you entered and any resulting messages?

**Comment by darnoceloc** [comment]
There are no files written to the current directory. There is no output/message from the command, after it is entered a new/blank terminal line appears.

**Comment by ajjackson** [comment]
That sounds very strange. What command did you type? What path do you get if you type `which sumo-kgen`?

**Comment by ajjackson** [comment]
Then your shell is not finding the program. I don't know why it isn't giving an error message when you try to run the program and it is not found, a shell would normally do that. What operating system and shell are you using? Do other programs work from this command line?

**Comment by darnoceloc** [comment]
I'm using ubuntu's (v.17.10) default GNOME terminal.
Yes, other programs do work from this terminal, I should note that pip3 install returned an error but pip install does not.
Pip install just returns a series of requirement already satisfied lines.
_**~$ pip3 install --user sumo**_
_**bash: /usr/local/bin/pip3: /usr/bin/python3.5: bad interpreter: No such file or directory**_

**Comment by ajjackson** [comment]
I'm not familiar with miniconda, but I think you need to add its binary folders to your PATH. Maybe sumo was installed somewhere like ~/miniconda3/bin or ~/.local/bin.

**Comment by darnoceloc** [comment]
When I search my hard drive for 'sumo' related files, nothing comes up.
I created a symbolic link at python 3.5 which references my actual/current python 3.6 version in Miniconda to get rid of the pip3 install error mentioned above.
However, the installation still does not generate an actual sumo directory or binary.

**_The program 'sumo' is currently not installed. You can install it by typing:
sudo apt install sumo_**

**Comment by ajjackson** [comment]
I don't think that's how you're supposed to use Miniconda. I suggest you seek help from another conda user.

The Pip/setup.py installer will put the sumo tools in a "bin" folder which is defined by your Python environment. Adding that folder to your PATH is part of the process of setting up that Python environment, but sometimes this is not done.

> Requirement already satisfied: sumo in /home/darnoceloc/.local/lib/python3.6/site-packages (1.0.9)
From the log we can see that the library part of Sumo was installed under ~/.local/lib . Are you sure you don't have a ~/.local/bin folder?

**Comment by darnoceloc** [comment]
The two folders below along with their respective contents are indeed in the site-packages directory, I assume just the first folder (sumo) should be added to my PATH?

**_~/.local/lib/python3.6/site-packages/sumo
cli  electronic_structure  __init__.py  phonon  plotting  __pycache__  symmetry
~/.local/lib/python3.6/site-packages/sumo-1.0.9.dist-info
DESCRIPTION.rst   INSTALLER  metadata.json  top_level.txt
entry_points.txt  METADATA   RECORD         WHEEL_**

**Comment by ajjackson** [comment]
Not quite. The folder above it (site-packages) needs to be on your PYTHONPATH. It might already be on that search path though (again, your Python distribution is _supposed_ to set this up for you); try `python3 -c "import sumo; print(sumo.__file__)"`. If that shows you the init file, you don't need to change PYTHONPATH. If it gives an ImportError then add site-packages to PYTHONPATH. (This is not ideal though as it could add some python3-only packages to your path for Python2 as well...)

There should be another directory somewhere called "bin" where executable scripts are located and this needs to be added to PATH. Try searching under ~/.local with the unix `find` command.

**Comment by darnoceloc** [comment]
This was result of the import/print functions you suggested.
/home/darnoceloc/.local/lib/python3.6/site-packages/sumo/__init__.py

The usr/bin directory which I assume is what you are referring to that contains all the executable scripts does not have any sumo related files.

**Comment by ajjackson** [comment]
I am not referring to /usr/bin, that is a system-level folder that would require admin privileges to write to. You installed the sumo library in a hidden folder (.local) within your own home folder (~ is a shorthand for /home/darnoceloc) so the binaries folder should also be somewhere in your home.

**Comment by darnoceloc** [comment]
The directory below contains sumo and phonopy executable scripts which correspond to the respective functions.
I assume you are implying I should add the export PATH line below to my .bashrc file, correct?
**_/home/darnoceloc/.local/bin
export PATH="/home/darnoceloc/.local/bin:$PATH"_**

**Comment by darnoceloc** [comment]
These are the contents of the sumo-kgen executable, it seems the python3.5 path must be modified since this is not my active/current python version.

 #!/usr/bin/python3.5

# -*- coding: utf-8 -*-
import re
import sys

from sumo.cli.kgen import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by darnoceloc** [comment]
Alright, up and running, Thanks!
I'm getting error, system is metallic when executing bandstats on a Silicon bandstructure xml file.
I want to calculate the band effective masses which can be utilized to estimate the Fermi level as a function of temperature.
Can you comment on the accuracy/suitability of sumo for these sort of calculations compared to boltztrap and/or pymatgen?

**Comment by ajjackson** [comment]
Bandstats estimates the effective mass by least-squares-fitting a parabolic or non-parabolic model to the band edges of a calculation. As long as all the appropriate dirextions are in the band structure and the Vasp calculation itself is of high quality, the accuracy should be pretty good. @utf may be able to comment on the camprison with Pymatgen and Boltztrap

For a wider range of effective mass schemes and Fermi level estimation you may be interested in github.com/lucydot/effmass but that package is a Python *library* and the user is expected to be comfortable in a Python environment.

Re: your metallic silicon, what does the band structure look like?

**Comment by utf** [comment]
Hi @darnoceloc, that sounds like you have an issue with your VASP calculation. We use pymatgen for loading the band structure, so if sumo says it is metallic then pymatgen will do to. I would check that you don't have partial occupancies (e.g. if your `SIGMA` is too big) and your choice of exchange-correlation functional.

I'm closing this issue because your installation problem is now solved. If you check the band structure, partial occupancies, and functional and still believe sumo has a bug please feel free to raise a new issue.
