### ISSUE TITLE
Dielectric loss function

### ISSUE THREAD

**Issue by keeeto** [SMTG-UCL/sumo#22]
I have written some functionality to plot dielectric loss functions, which could be useful in the code.
A lot of the functionality is replication of the absorption plotting. I have taken the lazy route of copying and modifying the absorption routines rather than extending the existing routines.

I am not sure what your stance is on this. I would guess that the easiest route is to create a Pull Request and allow you to review the code and decide from there.

**Comment by utf** [comment]
Hi @keeeto. This sounds awesome. Please submit a pull request we'll try and get it merged as soon as possible.

**Comment by ajjackson** [comment]
If you already have the changes on a branch of your own copy of the repo:

- Make a fork on your own Github space with the "fork" button on the sumo project
- Change your "origin" remote to point at your fork (`git remote set-url origin <new-url>`) and push up the changes
- If you need to pull in any updates from our master you can add the upstream as another remote with `git remote add upstream https://github.com/smtg-ucl/sumo.git` (or something like that!) and update from it with e.g. `git pull upstream master`
- When you push to your feature branch on Github, if you navigate to the Github page you'll see a little banner offering a button to make a pull request from your branch to the upstream project.

**Comment by keeeto** [comment]
:) thanks I was literally looking this up on Goolge half an hour ago!

**Comment by ajjackson** [comment]
Ok, from the discussion on the pull request #23 , it looks like we should be supporting a wider range of optical properties. The suggested list was

- Dielectric tensor (real and imaginary)
- Refractive index
- Optical conductivity
- Absorption
- Loss

As the plot options are essentially the same for all of these, these should be lumped together in a single plotter. The discussion also hits on possibilities for specifying multiple plots for double-y-axis plotting.
Personally, I'm not a big fan of double-y-axis plots for this kind of spectral data. If the y values aren't comparable, there's little gained by putting them on the same axes vs stacking separate axes.

I have two proposals:
### 1 Stacking up optional plots
Create a vertical sequence of all the requested plots. They could even be in the requested order:
```
sumo-optplot --xmax=10 absorption ri loss
```
![opt1](https://user-images.githubusercontent.com/2511383/43717337-208191c4-997f-11e8-89c7-297331e3d481.png)

Pros: simple to implement, predictable behaviour
Cons: Column could get unwieldy if you specify lots of plots, can't do any special combinations

### 2 All or one
Accept a single option for the plot type. Have a special case 'all' which does some nice arrangement of all of them. This could even be the default.
![opt2](https://user-images.githubusercontent.com/2511383/43717384-46f2470e-997f-11e8-8e9c-164d2286dabd.png)

Pros: can use colour and layout in a more thoughtful way. More potential for "beautiful by default" which is the Sumo way.
Cons: Less adjustable. In practice, the "all" plot would be good during investigation and for presentations, but you'd usually want a combination of singles for paper publication.

**Comment by ajjackson** [comment]
Just an update to say that I've made progress on the Questaal interface of Sumo to load in the frequency-dependent dielectric matrix and plot absorption. So there is now an increased incentive to develop this feature as we can add functionality to two /ab initio/ codes at once!

**Comment by ajjackson** [comment]
Implemented in #23
