### ISSUE TITLE
Missing style files

### ISSUE THREAD

**Issue by obaica** [SMTG-UCL/sumo#25]
using the bandplot function in the latest version sumo, it may cause some errors.  These files (*.mplstyle) need to be added in the following PATH.
`/home/tg/.local/lib/python3.6/site-packages/sumo/plotting/sumo_base.mplstyle`

**Comment by obaica** [comment]
![high symmetry kpoints issue](https://user-images.githubusercontent.com/22672466/44139312-4c6f4c28-a0a9-11e8-97fd-4e778b7f59fd.png)
In addition, If the distance between the two high symmetry points is very close, the following problem will occur in plotting.

**Comment by ajjackson** [comment]
(Moving the second comment to a new Issue as it is unrelated.)

**Comment by ajjackson** [comment]
Thank you for letting us know about the missing style files, we should be able to fix that and test for it.

**Comment by ajjackson** [comment]
This should be fixed on master now, just needs uploading to PyPI.

**Comment by obaica** [comment]
ok, thanks, now, it work well.

**Comment by ajjackson** [comment]
Great!
