### ISSUE TITLE
Plot bandstructure generated with 0-weight SC procedure

### ISSUE THREAD

**Issue by lucydot** [SMTG-UCL/sumo#30]
I would like to plot a bandstructure which has been generated using the 0-weight (fake) SC procedure outlined [here](https://cms.mpi.univie.ac.at/wiki/index.php/Si_HSE_bandstructure). It would be useful if there was a `sumo-bandstats` option to plot only the zero-weighted k-points. I'm happy to try and implement this if you could confirm that this is not already possible and agree that this would be a useful enhancement.

**Comment by ajjackson** [comment]
Not only can `sumo-bandplot` already do this, `sumo-kgen` is actually designed to help set up these calculations!

https://sumo.readthedocs.io/en/latest/sumo-kgen.html#hybrid-band-structures

**Comment by ajjackson** [comment]
We recently got a fix put in Pymatgen so this method can be used for meta-GGA calculations as well as hybrids. This may not have hit the release version of Pymatgen yet.

**Comment by lucydot** [comment]
I assume that pymatgen/sumo works out which k-points to plot automatically, as I can't see user options in the documentation. However, this does not seem to be working for a PBEsol with SoC calculation I am trying to plot - it is plotting all of the points. I've attached the vasprun.xml, KPOINTS and sumo output files. I've also included the bandstructure generated using [effmass](http://github.com/lucydot/effmass) (which reads from the OUTCAR and PROCAR) - one plot includes all k-points, and one includes only the zero-weighted k-points.
[sumo_issue_30.zip](https://github.com/SMTG-UCL/sumo/files/2441741/sumo_issue_30.zip)

**Comment by scanlond** [comment]
Hi Lucy,

For a PBEsol calculation, you don't need zero weighted k-points, and you
should just calculate the band structure self consistently using only the
k-points for the directions you want, all weighted properly. So this is
probably why SUMO plots all of the k-points, as these should all be valid.

Best wishes

David

**Comment by lucydot** [comment]
Hi David,

Thanks - pymatgen source code confirms your suggestion [here](http://pymatgen.org/_modules/pymatgen/io/vasp/outputs.html#Vasprun.get_band_structure). To avoid re-doing the calculation I used an easy workaround: Setting `LHFCALC` equal to `T`(rue) in the vasprun.xml tricked pymatgen into thinking it was a hybrid calculation and the bandstructure is looking great!

**Comment by ajjackson** [comment]
This is the Pymatgen bug I mentioned, which has been fixed but presumably isn't in the main release yet. Try using the latest version of pymatgen from source?
