### ISSUE TITLE
Automatically generate plot caption

### ISSUE THREAD

**Issue by utf** [SMTG-UCL/sumo#37]
Might be nice for sumo to automatically generate a figure caption for each plot.

**Comment by ajjackson** [comment]
Would the text be supplied by the user or would it just be very generic?

**Comment by utf** [comment]
The text would be very generic. But we probably could extract a lot of information from the vasprun. For example, it should be feasible to generate captions like:

> Band structure of TiO2, calculated using HSE06. The valence band maximum is set to zero eV. Valence and conduction bands shown in blue and orange, respectively.

Etc for spin-polarized, DOS and optics plots. Can also use the `latexify` function in Pymatgen to generate LaTeX ready captions.
