### ISSUE TITLE
Cannot plot the band structure 

### ISSUE THREAD

**Issue by kuangyia** [SMTG-UCL/sumo#39]
Dear all,

I just installed sumo on my operation system (windows 7).  

However, when running the command "sumo-bandplot -h" in the cmd, it can not give the band structure plot as expected and the error "no such command" pops out. Anyone knows what's going on ? Thanks in advance.

Best regards

**Comment by kuangyia** [comment]
Sorry, previously I said sth wrong, not 'sumo-bandplot -h", the correct one is "sumo-bandplot" (I was running this command in the directory where the vasprunxml file was saved.

**Comment by ajjackson** [comment]
"No such command" sounds like tbe program isn't on the path. What python emvironment do you have and what command shell are you entering these commands in? How did you install Sumo?

Our development/testing is done with Linux, OS X and the Windows Subsystem for Linux. Running directly in Windows isn't really tested but it *should* be possible.

**Comment by kuangyia** [comment]
I install sumo following the instructions given in your GitHub. My python is python3.6 installed with Minidconda3 and I used the shell "cmd" default in windows 7 to enter these commands in. Maybe as you said, I did not set the sumo path in the system environment. I will have a try and let you know if it works or not.

**Comment by kuangyia** [comment]
Thanks for your comments. I still failed to run commands by setting the program path. Finally I uninstall sumo and reinstall again and now it has no problem. I speculate sth wrong with the previous installation.

**Comment by ajjackson** [comment]
Glad to hear it's working :-)

We considered to give more specific details of how users should set up their acientific python environment, but decided against it because having so many conflicting suggestions from different projects means that beginners are likely to end up with a big mix of different installations.
