### ISSUE TITLE
having issue with the sumo-bandplot command

### ISSUE THREAD

**Issue by Anower120** [SMTG-UCL/sumo#41]
I tried to plot band structure with the **sumo-bandplot** command, but received the following error message:

Traceback (most recent call last):
  File "/lustre/home/mdhossa55/anaconda3/bin/sumo-bandplot", line 11, in <module>
    load_entry_point('sumo==1.1.2', 'console_scripts', 'sumo-bandplot')()
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/sumo-1.1.2-py3.6.egg/sumo/cli/bandplot.py", line 467, in main
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1143, in resource_filename
    self, resource_name
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1650, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1671, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'sumo.plotting/orbital_colours.conf'

Could you please let me the possible steps to fix this? Many thanks in advance!

Kind regards,
Anower

**Comment by utf** [comment]
It looks like our `Manifest.in` is very out of date. I wonder if this could be causing the issue.

I'll update the manifest and push a new version later tonight. Hopefully once you reinstall that should fix any issues.

**Comment by utf** [comment]
I've pushed a new version to Pypi. If you try reinstalling hopefully that will fix your issue.

**Comment by mukhtarbayerouniversity** [comment]
Hello,
Please, i want to plot band structure from HSE06 calculations. do i need to delete the IBZKPT part in the KPOINTS or plot together with it? Thank you.

**Comment by ajjackson** [comment]
You should not modify the KPOINTS file after performing the band structure calculation; sumo-bandplot will ignore the extra points.

NB new questions like this one should be posted as a fresh Issue page; it prevents discussions getting complicated and makes them easier to track.

@Anower120 did the update to sumo fix your problem?

**Comment by Anower120** [comment]
> You should not modify the KPOINTS file after performing the band structure calculation; sumo-bandplot will ignore the extra points.
> 
> NB new questions like this one should be posted as a fresh Issue page; it prevents discussions getting complicated and makes them easier to track.
> 
> @Anower120 did the update to sumo fix your problem?

@ajjackson Yes, it works perfectly :) Thank you so much for your kind supports on this.

**Comment by Anower120** [comment]
@ajjackson Yes, it works perfectly :) Thank you so much for your kind supports on this.
