### ISSUE TITLE
ImportError: cannot import name 'gcd'

### ISSUE THREAD

**Issue by obaica** [SMTG-UCL/sumo#44]
> [root@centostg gt]# sumo-kgen
> Traceback (most recent call last):
>   File "/root/.local/bin/sumo-kgen", line 7, in <module>
>     from sumo.cli.kgen import main
>   File "/root/.local/lib/python3.4/site-packages/sumo/cli/kgen.py", line 23, in <module>
>     from sumo.symmetry.kpoints import get_path_data, write_kpoint_files
>   File "/root/.local/lib/python3.4/site-packages/sumo/symmetry/__init__.py", line 9, in <module>
>     from sumo.symmetry.kpath import Kpath
>   File "/root/.local/lib/python3.4/site-packages/sumo/symmetry/kpath.py", line 14, in <module>
>     from pymatgen.core.structure import Structure
>   File "/usr/lib64/python3.4/site-packages/pymatgen/__init__.py", line 55, in <module>
>     from pymatgen.core import *
>   File "/usr/lib64/python3.4/site-packages/pymatgen/core/__init__.py", line 8, in <module>
>     from .structure import Structure, IStructure, Molecule, IMolecule
>   File "/usr/lib64/python3.4/site-packages/pymatgen/core/structure.py", line 18, in <module>
>     from math import gcd
> ImportError: cannot import name 'gcd'

> [root@centostg gt]# pip install gcd
> Requirement already satisfied: gcd in /usr/lib/python3.4/site-packages (0.1.0)
> Requirement already satisfied: Click>=6.0 in /root/.local/lib/python3.4/site-packages (from gcd) (7.0)

**Comment by utf** [comment]
You are using Python 3.4 but sumo is only supported on Python 3.5 and above. Updating python should fix your problem.
