### ISSUE TITLE
sumo-phonon-bandplot "--dim" odd supercell shapes compatibility

### ISSUE THREAD

**Issue by badw** [SMTG-UCL/sumo#47]
To whom it may concern,

At the moment `sumo-phonon-bandplot` only seems to be able to pass 3 numbers to `--dim`, and it would be nice to pass 9 numbers such as `3 2 -1 0 1 3 0 0 1` for instance as you can in `phonopy`. 

Yours concernedly,
A concerned user.

**Comment by ajjackson** [comment]
It should already be on master, just hasn't made it into release yet: https://github.com/SMTG-UCL/sumo/commit/6176c6aff0ddbba6194695ab15361a29447b9bc8
