### ISSUE TITLE
Correct NEDOS

### ISSUE THREAD

**Issue by SidraFirdous** [SMTG-UCL/sumo#49]
Dear all,
Sumo - Great program. Thank you for writing it and making it available.

What are the optimum INCAR settings you would suggest when running a DOS job. For example my INCAR has a setting of:
  
>  EMIN = -30.0              #Minimum range energy for DOS carefull must have decimals
>     EMAX = 15.0               #Maximum range energy for DOS carefull must have decimals
>     NEDOS = 4000               #Number of DOS sample sites

and there is a lot of noise in the plot. (plot attached)

Your example figures really look smooth and nice.

Thanks & Regards.

[dos.pdf](https://github.com/SMTG-UCL/sumo/files/2956227/dos.pdf)

**Comment by badw** [comment]
You can add Gaussian smearing by doing `sumo-dosplot -g 0.2` (0.2eV smearing) which will make it nice and smooth

**Comment by SidraFirdous** [comment]
Thank you for the swift response. I have got a nice smooth figure now.

**Comment by ajjackson** [comment]
Smooth plots will also be obtained if the calculation used a lot of broadening in the ISMEAR/SIGMA settings. However, as it is possible to choose the level of broadening at plot-time with the -g option I would recommend to use tetrahedron integration (ISMEAR=-5) when calculating the DOS without structure optimisation.

**Comment by SidraFirdous** [comment]
> My earlier INCAR settings did use the tetrahedron method. Maybe my sigma value was too low?
> 
> #DOS related values
>    ISMEAR = -5; SIGMA = 0.10  #broadening in eV -4-tet -1-fermi 0-gaus, -5=DOS
>     EMIN = -30.0              #Minimum range energy for DOS carefull must have decimals
>     EMAX = 15.0               #Maximum range energt for DOS carefull must have decimals
>     NEDOS = 4000               #Number of DOS sample sites
>     LORBIT = 11               #Instruction to construct the partial DOS
>     NPAR = 1                  #DOS calculation does not run in pararell

**Comment by ajjackson** [comment]
As far as I know SIGMA does nothing when using Tetrahedron integration
