### ISSUE TITLE
Issues in optplot

### ISSUE THREAD

**Issue by utf** [SMTG-UCL/sumo#50]
The refactoring of the optics modules seems to have introduced a number of bugs:

- The `--bandgap` option throws an error.
- When plotting multiple systems simultaneously the output files are named incorrectly: Somehow I now have `absorption_0.dat` and `absorption_0.dat_1.dat`.
- For plotting multiple systems, the automatic label generation no longer works. Previously, it would assign the label as the latex formatted composition. Now it just lists the materials as "1", "2", "3".

**Comment by ajjackson** [comment]
Ok, some labelling things to work on then! I guess the `--bandgap` option only makes sense for absorption plots really. Should we ban it from multiplots?

**Comment by ajjackson** [comment]
Pushed some stuff to master:
- fixed an argparse problem
- fixed the `--bandgap` option
- fixed the dat file naming, and made the numbering start at 1 while I was at it

Automatic naming could be tricky to maintain if we support multiple calculators. I'm not even convinced it's _that_ useful as you'll usually get an out-of-order representation of the stoichiometry and can't distinguish between different phases of the same material. But I guess it's doable? Removing "bug" label as this is more of a "regression"...

I'd also like to rename the image files from "absorption.ext" to "optics.ext" but held off that initially for backwards compatibility.

**Comment by ajjackson** [comment]
Hmm, the automatic naming does seem to be working for me on Questaal branch actually! All the more reason to get on with merging it?

**Comment by utf** [comment]
Thanks Adam!

Ok, I'm aiming to do a full code review on the questaal PR next week.

**Comment by ajjackson** [comment]
Great! I'll hold off that merge then :-)
