### ISSUE TITLE
There no f_0 orbital in f electron  system

### ISSUE THREAD

**Issue by zrqustc** [SMTG-UCL/sumo#52]
When I use sumo plot pdos, I can not find f_0 orbital, Could you give me some suggestion?
As we know, there are 7 orbitals for f electrons,but I can not find f_0 orbital.
Is it  a bug or something  I did wrong?
please see the following:

![image](https://user-images.githubusercontent.com/16348056/59011310-dc0da900-87f9-11e9-94cb-1cf688cc7bc2.png)
This script  I use：

dosplot(filename="/scratch/rqzhang/SmB6/SQS/222/MAE/vasprun.xml",
        width=a,height=b, lm_orbitals=({'Sm': ('f')}),elements=({"Sm":'d'}),ylabel='PDOS (a.u.)',
        legend_cutoff=3,
        xmin=-1.5, xmax=0.5,num_columns=1, plot_total=True,legend_frame_on=True

**Comment by utf** [comment]
If you set `legend_cutoff=0` that should show all the orbitals. Currently, orbitals with contributions of less than 3% to the DOS in the energy range are not given a label.

**Comment by zrqustc** [comment]
Thanks so much for your reply.

So this following figure I set legne_cutoff=0, there is also no f_0 orbitals.

![image](https://user-images.githubusercontent.com/16348056/59051974-abf2f400-8853-11e9-8449-2fb7fc06e82c.png)

**Comment by utf** [comment]
Thanks for your quick feedback. I fixed the bug in the latest version. If you update sumo using the latest version on GitHub, that should fix your problem.

Please let me know if it works.

**Comment by zrqustc** [comment]
That is great! Thanks so much, I will test using the latest version. Thanks.

**Comment by zrqustc** [comment]
I have tested the pdos using the latest version. It fixed my problem.  Thanks so much for your nice help. By the way, could you tell me which module you changed, I have not find the bug. Thanks!

**Comment by utf** [comment]
No problem. The bug was fixed in this commit: c1703b5a896d15f344d718112e9a4ac61811b6c2
