### ISSUE TITLE
possibility to project a single atom in band structure

### ISSUE THREAD

**Issue by badw** [SMTG-UCL/sumo#54]
it might be a bit niche, but I was wondering whether it was possible to project a single atom, e.g. `Bi.5` (potentially even Bi.5.s.p.d) on the band structure? I know this is something you can do with the DOS options but I was thinking it would be nice to see on the actual bands.

**Comment by utf** [comment]
you should be able to do this using the "stacked" projection mode. E.g. just add `--mode stacked` to the end of your plotting command.

**Comment by ajjackson** [comment]
Assuming resolved, Ben knows where to find us if not ;-)
