### ISSUE TITLE
`sumo-dosplot` now plots y-axis values for Arb. Units (possibly recent Matplotlib update?)

### ISSUE THREAD

**Issue by badw** [SMTG-UCL/sumo#55]
`sumo-dosplot` now plots y-axis values where previously there wouldn't be any (see below) 

just thought I would let you know!

Cheers!

![dos](https://user-images.githubusercontent.com/14872755/59695441-88805f80-91ea-11e9-8f1f-e0fa09c5e603.png)

**Comment by ajjackson** [comment]
Can reproduce with matplotlib 3.1.0, not the previous version 3.0.3.

It's weird, the only thing I see in the release notes that could be relevant is a change to minor tick spacing. https://matplotlib.org/3.1.0/users/whats_new.html#adjust-default-minor-tick-spacing

**Comment by ajjackson** [comment]
I think I got it. Quick fix has been pushed to Master, give it a try?

**Comment by badw** [comment]
yep seems to be working! thanks!
