### ISSUE TITLE
legend problem when total DOS is removed

### ISSUE THREAD

**Issue by iyavuz80** [SMTG-UCL/sumo#56]
Hello, the sumo code is extremely useful and I find it very user friendly. I noticed that when I use 
"--no-total" the code shows the info from all atoms including even DOS less than 3% ie the default value, this makes the legend and graph so cluttered. Specifically, is it possible to remove the legend and/or solve this problem? Thanks in advance.

**Comment by ajjackson** [comment]
I can reproduce this with the Cs2SnBr6 sample data. It definitely isn't supposed to do that!

**Comment by ajjackson** [comment]
https://github.com/SMTG-UCL/sumo/blob/master/sumo/plotting/dos_plotter.py#L164 seems relevant

**Comment by iyavuz80** [comment]
ok thanks. i'll work on it.

Adam J. Jackson <notifications@github.com>, 5 Tem 2019 Cum, 15:13 tarihinde
şunu yazdı:

**Comment by ajjackson** [comment]
I just put in my own PR, but would be happy to see a smarter alternative!

**Comment by iyavuz80** [comment]
ok thanks

5 Tem 2019 Cum, saat 15:23 tarihinde Adam J. Jackson <
notifications@github.com> şunu yazdı:

**Comment by ajjackson** [comment]
Fix is in Master
