### ISSUE TITLE
a bug in kgen.py

### ISSUE THREAD

**Issue by flower0226** [SMTG-UCL/sumo#6]
hi there
thanks u guys offer such a best code lol
help us a lot!
there is a bug while using sumo-kgen --density, which can't change density
suggest u guys to modify 'sumo/cli/kgen.py' according to the following lines:
106     kpath, kpoints, labels = get_path_data(poscar.structure, mode=mode,
107                                            symprec=symprec,line_density=density,
108                                            kpt_list=kpt_list,
109                                            labels=labels)

**Comment by ajjackson** [comment]
Is the fix working for you?

**Comment by utf** [comment]
Hi @flower0226.

Thanks for noticing this. We actually fixed this yesterday on GitHub but I didn't publish a new version to Pypi.

I've updated the Pypi release, so if you update it should work now.
