### ISSUE TITLE
Add support for lobster plots

### ISSUE THREAD

**Issue by utf** [SMTG-UCL/sumo#60]
Pymatgen now handles LOBSTER inputs and outputs. Additionally, LOBSTER now supports k-dependent orbital projects.

Apparently the orbital projection is better than the default in VASP.

We should add a lobster plotter module to sumo, with support for the following plots:
- Orbital projected DOS and band structures using LOBSTER decomposition.
- Bonding/antibonding projected band structure and density of states plots.

**Comment by ajjackson** [comment]
Would be cool to get bring in COHP and COOP plots :-)

**Comment by utf** [comment]
One other thing I've just read is that LOBSTER supports rotating the basis set. This means we can finally get correct lm decomposed orbitals for free (e.g. px, py, pz) without having to rerun the calculation with an oriented POSCAR.

**Comment by obaica** [comment]
I think this is a great job!

**Comment by kavanase** [comment]
Adding support for `LOBSTER` in sumo (using the `pymatgen` modules) would be a great addition!  For example a band-structure with the orbital-projected bonding/anti-bonding DOS alongside (similar to the current implementation of a DOS alongside the bandstructure) would be really nice and useful to be able to do!

**Comment by ajjackson** [comment]
Update on this: lobsterpy has been released, which provides command-line tools and plotting for LOBSTER outputs using Pymatgen https://github.com/JaGeo/LobsterPy . This tool was developed by @JaGeo to perform automatic analysis and makes some useful decisions for the user.

I implemented matplotlib stylesheet support in a similar fashion to Sumo, so while there is not yet a way to directly plot e.g. COHP alongside bands, it should be straightforward to generate plots with a consistent style for publication when using LobsterPy and Sumo for the same project.

If we _do_ still want a COHP mode in bandplot, it should probably be a basic call to lobsterpy's "automatic-plot" features. Beyond that a lot of extra arguments would be needed to select things, and the bandplot parser is already quite complex.

**Comment by ajjackson** [comment]
Closing for now, recommend people use LobsterPy. Can re-open / start new issue if demand is there for combination band/COHP plots, but I would note it overlaps with a more general "advanced DOS with bands" which will be a tricky UI problem.
