### ISSUE TITLE
Pymatgen requiring Python 3.6?

### ISSUE THREAD

**Issue by ajjackson** [SMTG-UCL/sumo#62]
[This build is blowing up](https://travis-ci.org/SMTG-UCL/sumo/jobs/554619347) because Pymatgen is using f-strings which are only available in very recent Python versions. Should/can we pin Pymatgen to a compatible version in setup.py?

**Comment by ajjackson** [comment]
Issue opened on Pymatgen tracker: https://github.com/materialsproject/pymatgen/issues/1522

**Comment by ajjackson** [comment]
It looks like there is a way to set different dependencies in the sumo _setup.py_ depending on the local Python version. https://www.python.org/dev/peps/pep-0508/#environment-markers

Much as I would like to use f-strings it seems a bit early to drop Python 3.5 for sumo if we can avoid it: many of our users are running it on cluster head nodes which have a limited selection of Python modules.

**Comment by ajjackson** [comment]
Pymatgen team has confirmed their move to 3.6 ([Issue](https://github.com/materialsproject/pymatgen/issues/1522)) and put the requirement in setup.py.

We have two options:
- Make Python 3.6 a hard requirement for Sumo as well (as I said in that Issue I think this is ok for our users but it's a bit tight for comfort.)
- Try and do some setup.py magic to pin 3.5 users to an older version of Pymatgen. This could be a problem as quite a few bugs/feature-requests in sumo have been addressed by making changes to Pymatgen...

Maybe do a numbered 3.5-compatible release of Sumo that pins to an appropriate Pymatgen version, then move further Sumo development to 3.6-only? That way people on 3.5 have a known sumo version number they can safely install.

**Comment by utf** [comment]
I also think Python 3.6 is a little close for comfort.

I like the idea of a numbered 3.5 compatible release.

**Comment by ajjackson** [comment]
Closing as the immediate issue has been fixed. We still need to plan a "final 3.4 release" before things diverge too far.
