### ISSUE TITLE
Overlay multiple phonon band structures

### ISSUE THREAD

**Issue by ajjackson** [SMTG-UCL/sumo#65]
I thought we already had an issue for this but don't see it.

This feature was previously discussed with @kinzani @meinhorn @warda-rahim @zccaayo  
and is particularly relevant for calculations in the Quasi-harmonic approximation: accept multiple sets of phonon data and plot them in different colours on the same band structure.

This may be achieved using the existing Python API, without much issue for e.g. supercell size convergence. However, for QHA calcs there is an interesting artefact that emerges: slight differences in lattice parameters lead to slightly inequivalent reciprocal-space paths. The "absolutely correct" solution here is to refuse to plot different lattices on the same band structure as the axis becomes technically incorrect. The pragmatic "let's actually do science here" solution is to arbitrarily choose one of the structures and rescale the reciprocal lattice for the others so the features at high-symmetry points may be compared easily.

**Comment by ajjackson** [comment]
Curious as to whether @utf already encountered/solved this in a script and it just hasn't made it back into 
sumo yet.

**Comment by utf** [comment]
@ajjackson  I had a script to do it but this was pre sumo supporting band structures.

The "best" solution, in terms of what users will expect, would be to rescale one of the lattices to match the other. I guess we need to check that both structures have the same space group.

**Comment by ajjackson** [comment]
Yup! And if the phonon band structure is read in directly (rather than generating it with Phonopy) then we should check that the paths are actually the same.

I would very much like to compare phonon band structures from Castep/DFPT and Vasp/Phonopy :smile:

**Comment by meinhorn** [comment]
Hey all - this is @meinhorn. Since I have absolutely no clue what y'all are
talking about I'm guessing I'm not the guy you intended to include in this
thread...

**Comment by ajjackson** [comment]
Apologies! It was @meinhorn1

**Comment by ajjackson** [comment]
Thinking about this some more, it really would be useful to compare phonon band structures from calculations with different supercells etc. - in which case the command syntax is going to get rather awkward. How about:

- add a `--to-json` option which dumps the Pymatgen object
- add a `--from-json` option which zips with `--labels` to add a set of overlaid plots? (And handles label consistency, axis rescaling.)

So the workflow lets you compare to a previous plot(s) while setting up a new one (e.g. getting the supercell details right). When you're happy with them you can run `sumo-phonon-bandplot` with _just_ json files to get your final comparison. The other data-related arguments will always refer to a single dataset you are setting up right now. Plotting-related arguments don't end up in the JSON and refer to the plot file you are currently generating.
