### ISSUE TITLE
Many non-optional optional arguments

### ISSUE THREAD

**Issue by shyamd** [SMTG-UCL/sumo#7]
I'm trying to use this right now and I'm finding that a lot of "optional" args are actually required with defaults that are in the CLI code. For instance the dos_options in the bandstructure/dos plotting is by default None in the code. This breaks and I have to set it to a series of values I figured out by scouring the CLI code. The methods should initialize to intelligent defaults if not specified.

**Comment by ajjackson** [comment]
Thank you for using Sumo! That doesn't sound ideal, we'll take a look at this.

**Comment by utf** [comment]
Hi @shyamd 

This is a bug. There shouldn't be any optional arguments that require modification for the code to run without an error. In general, I've tried to make the default value for the optional arguments the same as the default in the command line scripts.

The `dos_options` is a special case, in that it is the only optional argument that can accept a dictionary containing sub-options. You shouldn't have to look through the CLI code to see what the valid keys for this dictionary are. There are detailed in the docstring for the function, namely:

```python
            dos_options (:obj:`dict`, optional): The options for density of
                states plotting. This should be formatted as a :obj:`dict`
                containing any of the following keys:
                    "yscale" (:obj:`float`)
                        Scaling factor for the y-axis.
                    "xmin" (:obj:`float`)
                        The minimum energy to mask the energy and density of
                        states data (reduces plotting load).
                    "xmax" (:obj:`float`)
                        The maximum energy to mask the energy and density of
                        states data (reduces plotting load).

                    ... etc
```

I've fixed the bug you mentioned (namely that supplying `None` for `dos_options` doesn't work). The following code snippet should now successfully produce a combined band structure and dos plot:

```python
from pymatgen.io.vasp.outputs import BSVasprun
from sumo.electronic_structure.dos import load_dos
from sumo.plotting.dos_plotter import SDOSPlotter
from sumo.plotting.bs_plotter import SBSPlotter

vr = BSVasprun('vasprun.xml.gz')
bs = vr.get_band_structure(line_mode=True)

dos, pdos = load_dos('vasprun.xml.gz')
dos_plotter = SDOSPlotter(dos, pdos)
bs_plotter = SBSPlotter(bs)

plt = bs_plotter.get_plot(dos_plotter=dos_plotter)
plt.savefig('band_dos.pdf', bbox_inches='tight')
```

----

You mentioned that you had found several cases where the default optional arguments didn't work. Would you be able to tell me the others so I can fix that behaviour.

Cheers!

**Comment by shyamd** [comment]
That actually fixed all my other optionals as well. I think this one looks good.
