### ISSUE TITLE
Possibility to represent spin up and Spin down bands differently

### ISSUE THREAD

**Issue by aizardar** [SMTG-UCL/sumo#70]
Hi, thank you for a wonderful code.
I was wondering if it is possible to represent spin up and spin down bands separately ?
Thanks

**Comment by ajjackson** [comment]
Separate colours or separate plots?

**Comment by aizardar** [comment]
Hi, thanks for your message. Separate plot would be nice.

**Comment by ajjackson** [comment]
This seems a bit esoteric to add as a standard feature, but I can advise on how to modify the code to achieve it for your purposes. The `sumo-bandplot` program is essentially a link to _sumo/cli/bandplot.py_, so you can copy this file to make modified versions of the program. If you look at line 288
```plotter = SBSPlotter(bs)```
this is where we lose our last chance to modify the band structure data before the plotter is setup. 

Before that line you could insert
```python
    bs.is_spin_polarized = False
    del bs.bands[Spin.down]
```
to plot only the spin-up channel, or
```python
    bs.is_spin_polarized = False
    bs.bands[Spin.up] = bs.bands[Spin.down]
    del bs.bands[Spin.down]
```
to plot only the spin-down channel. (We move them to spin-up as this is where Sumo expects to find the data for a single-channel calculation.)

**Comment by ajjackson** [comment]
Hopefully that will do the trick for your purposes! Ideally we'd have a slightly nicer management of matplotlib Axis objects, allowing a Python script to point the plotting logic at its own Figure/Axes arrangement. I'm afraid at the moment _bandplot_ contains a lot of logic to handle the existing set of options so this separation is not a quick job.

**Comment by aizardar** [comment]
Hi, I tried and it works. Thanks for the help...

**Comment by ajjackson** [comment]
Glad to hear it. This is the sort of thing that should be easy to do from the Python API, so we'll keep that in mind when refactoring things. Happy plotting!
