### ISSUE TITLE
Plan to plot local electronic potential?

### ISSUE THREAD

**Issue by Nokimann** [SMTG-UCL/sumo#72]
I saw your comment on my issue in pymatgen, and come here. Thank you for a handy SUMO. 

I want to know you have any plan to plot local electronic potential?

**Comment by ajjackson** [comment]
Perhaps you would be interested in [Macrodensity](https://github.com/WMD-group/MacroDensity), a package for import/averaging of LOCPOT data.

It's not quite as friendly as Sumo at the moment, but as far as I know this is what all the Sumo developers have been using for personal projects. There are quite a few example scripts that can be copied/edited for individual purposes.

@keeeto

**Comment by keeeto** [comment]
@ajjackson thanks for the mention. For sure Macrodensity is not up to Sumo levels of user experience. However, @Nokimann it would be great if you tried out Macrodensity and leave us some feedback :)

**Comment by Nokimann** [comment]
Thank you both @ajjackson and @keeeto
I think I should use Macrodensity.

**Comment by Nokimann** [comment]
Thank you both @ajjackson and @keeeto
I think I should use Macrodensity.
