### ISSUE TITLE
Minor issue about font?

### ISSUE THREAD

**Issue by Nokimann** [SMTG-UCL/sumo#73]
I've just installed SUMO and tested it.

```
sumo-dosplot
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
```

I'm using SUMO on Cent OS 7 though I found some solutions for Ubuntu OS.

**Comment by ajjackson** [comment]
That's not an error, just a warning that it couldn't find any of the preferred fonts. You can use the `--font` options in the sumo tools to choose your favourite font, or set it with style sheets. If you'd like to get a similar result to the examples and to papers from the Scanlon Materials Theory Group at UCL, try using Catamaran https://fonts.google.com/specimen/Catamaran (download from https://github.com/google/fonts/tree/master/ofl/catamaran ). You may need to refresh the Matplotlib fonts cache before they are found.

You can see the preferred font list in the [sumo base style sheet](https://github.com/SMTG-UCL/sumo/blob/master/sumo/plotting/sumo_base.mplstyle). I would expect most users to have Helvetica available so this message is not common, but I know from experience that on some Linux distributions the font names are slightly different and so Matplotlib may not find them from that list. If you look around online you should be able to find how to get a list of the fonts available to Matplotlib.

**Comment by Nokimann** [comment]
This can be closed.
