### ISSUE TITLE
One of legends is not appeared even if I didn't insert --no-legend flag

### ISSUE THREAD

**Issue by Nokimann** [SMTG-UCL/sumo#74]
I typed 

```
sumo-dosplot --element Mo.s.p.d,S --format png
```
![dos](https://user-images.githubusercontent.com/31014779/62835853-e6d03880-bc97-11e9-93ec-c02d0f629d19.png)

No legend of Mo (p) and S (d) in the dos figure. 

Here, the number of graphs is correct.
Also extracted data is ok.

What kind of output should I upload more?

[sumo.zip](https://github.com/SMTG-UCL/sumo/files/3490141/sumo.zip)

**Comment by Nokimann** [comment]
I found if I add --legend-cutoff 0 I properly worked again.

**Comment by Nokimann** [comment]
I didn't catch the documents with care sorry.

**Comment by ajjackson** [comment]
No worries! The `--legend-cutoff` option is there because it is surprisingly difficult to reason automatically about which items should be included.

You probably don't actually want to draw attention to S(d) in this case.
