### ISSUE TITLE
Fermi Energy level

### ISSUE THREAD

**Issue by xenhua** [SMTG-UCL/sumo#80]
Do the DOS plots prepared by sumo have the energy level translated to Fermi energy level, i.e., E - E_Fermi is the x-axis?

Attached is the plot I have obtained with the command "sumo-dosplot --atoms Ni.1.4.5 --gaussian 0.1" 
[dos.pdf](https://github.com/SMTG-UCL/sumo/files/3767692/dos.pdf)

Could you please shed some light on what exactly the legend for this plot (Total DOS, Ni(d)) mean?

Thank you so much.

**Comment by ajjackson** [comment]
Thank you for your interest in Sumo.

Energy axes of DOS and band plots are aligned such that the VBM=0 by default. We don't like to attach too much significance to the calculated E_Fermi from DFT calculations of semiconductors, as these are very sensitive to defects and surface effects in practice. Also, aligning to the VBM makes it easy to read bandgaps.

Sumo will plot all the requested contributions in a PDOS (in this case, the s, p, d orbitals of three summed Ni atoms), but uses a threshold to decide which lines are worth showing in the legend. So in this case the black line is the total DOS (over all atoms, orbitals), the brown line is the d orbitals of this Ni subset and the blue line is probably Ni-s states. You can change the tolerance for labelling with `--legend-cutoff`. In this case you might also like to hide the total DOS line using `--no-total` to get a more useful scale for the Ni contribution. See the [tutorial](https://sumo.readthedocs.io/en/latest/sumo-dosplot.html) for more examples.

There has been some discussion of making it easier to indicate the Fermi level when appropriate in this [pull request](https://github.com/SMTG-UCL/sumo/pull/68). It's on the wishlist!

**Comment by xenhua** [comment]
Thanks for your reply.

However, I would expect the major contribution to the DOS of selected Ni atoms to be from the d-orbitals of Ni.

I also checked my data file and my expectation seems to be confirmed by raw atom-splitted DOS data. Below is a line from my data file.

```
#Energy           s          py          pz          px         dxy         dyz         dz2         dxz         dx2       tot
-1.98337     0.79406     0.79710     0.53761     0.80242    13.52140    10.72380    11.02470    10.94670    13.51610    62.66390

```

There seems to be some discrepancy between my data file and the plot obtained from SUMO.

I am also attaching my DOSCAR here.
[DOSCAR.txt](https://github.com/SMTG-UCL/sumo/files/3771855/DOSCAR.txt)

Could you please let me know where I might be going wrong. 
Thank you so much.

**Comment by ajjackson** [comment]
What's the discrepancy? The brown region is the PDOS from d orbitals of those three atoms, the grey region is the total DOS over all 37 atoms in the unit cell. 37 atoms will contribute more states than 3 atoms, all other things being equal.

**Comment by xenhua** [comment]
> (in this case, the s, p, d orbitals of three summed Ni atoms

I misunderstood the total is also over the total (s+p+d) of the 3 summed Ni and not 37 atoms of the unitcell.

It would be more intuitive not to plot total dos when (atomic) projected local DOS is being requested

**Comment by ajjackson** [comment]
You can hide it with `--no-total`. I don't agree that this should be the default; in many cases is is useful to see what fraction of the total DOS comes from a particular contribution.
