### ISSUE TITLE
DOS from 2 calculations

### ISSUE THREAD

**Issue by xenhua** [SMTG-UCL/sumo#81]
Dear Sumo developers,

Is there any way I can use SUMO to plot DOS from two different calculations (as two different lines) in the same figure.

My analysis consists of showing the effect of an adsorbate on top of a surface. Therefore, I have two calculations: (a) without the adsorbate and (b) with the adsorbate.

It would be great if I can plot the DOS of these two calculations in one figure, side by side.

Thanks.

**Comment by ajjackson** [comment]
The quick option at the moment would be to make use of the .dat files that are generated with another plotting program (e.g. gnuplot, xmgrace or a python/matplotlib script). If you want to match the styling closely to Sumo you may find it useful to copy the matplotlib style files from _sumo/plotting_ .

It's worth thinking about this possibility a bit more, though. We recently implemented something similar for _phonon-bandplot_ which allows a .json file to be generated representing the current plot, and allows multiple .json files to be read in to create overlaid spectra.

It's fairly clear how this might work for TDOS calculations as multiple lines on the same plot. It's not so clear to me how to proceed in the case of PDOS calculations where there are many orbitals to consider: either we plot everything and the figure becomes very crowded, or we need to provide a way for the user to specify exactly which orbitals they want to compare. (The need for a clear syntax for PDOS specification seems to be a recurring challenge when thinking about new features.)

Alternatively if by "in one figure, side by side" you mean on two separate axes then this can be achieved with sumo using the Python API to plot to axes that you have already arranged as desired. Can you sketch/show an example of what you would like to see?

**Comment by ajjackson** [comment]
Closing for now as discussion has stalled and no action is due.

I do think there is potential for a more systematic approach to comparison plots in Sumo.
