### ISSUE TITLE
issue about sumo-optplot --font

### ISSUE THREAD

**Issue by GordonTong66** [SMTG-UCL/sumo#83]
Hi,

I understand that my font library may not contain sumo-preferred fonts. But even when I set manually like:

sumo-optplot --font /usr/share/fonts/dejavu/DejaVuSansMono.ttf

there's still error:

findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.

How can I deal with this issue? Thanks.

Yijun

**Comment by utf** [comment]
Hi Yijun,

I like the idea of being able to use font's like you suggested. Unfortunately, this isn't currently implemented.

The most reliable method I've found for using custom fonts in Matplotlib is:

1. Make a `.fonts` folder in your home directory if it doesn't already exist: `mkdir ~/.fonts`.
2. Copy your font to the directory. Note, I think matplotlib requires truetype fonts (`.ttf`).
3. Remove the matplotlib font cache: `rm -r ~/.cache/matplotlib`.
4. Reference the font by its full name: `sumo-optplot --font "DejaVu Sans Mono"

Does that work for you?

**Comment by GordonTong66** [comment]
Many thanks! This can be closed now.
