### ISSUE TITLE
Sumu-dosplot troubleshooting

### ISSUE THREAD

**Issue by alexey-krasnov** [SMTG-UCL/sumo#88]
Dear developers,
I have met two issues during DOS plotting:
1) When I did sumo-dosplot after my VASP calculations, I received the dos.pdf file (attached)
[dos.pdf](https://github.com/SMTG-UCL/sumo/files/3906848/dos.pdf). Also, I obtained several .dat files with numerical data. My question is why the data in these .dat files have a different energy range? For example, in DOS figure I have the energy range from -6 to 6 eV, but in these .dat files, the energy range is c.a. -3.4. to 6.9 eV.
2) I read that sumo-dosplot shifts the VBM/Fermi level to 0 eV by default. However, in my case, it doesn't work. I obtained the picture as is [dos.pdf](https://github.com/SMTG-UCL/sumo/files/3906855/dos.pdf).

Sincerely,
Aleksei

**Comment by ajjackson** [comment]
The .dat files use the whole energy range from the input data; they are intended for people making their own plots and so we give them as much as possible on the understanding that they will be able to choose the region of interest later. If you look at the DOSCAR it should have the same energy range (but shifted by the Fermi energy).

For #2, can you have a look at the reported Fermi energy and the spectrum given in DOSCAR? It might be that the calculation found a slightly low/metallic Fermi level.

**Comment by alexey-krasnov** [comment]
Thanks a lot! I got it.
