### ISSUE TITLE
Axis label options

### ISSUE THREAD

**Issue by ajjackson** [SMTG-UCL/sumo#9]
Raised by @shyamd in #8 :
> it might be a good idea to change the Energy Label to something like E-E_f (eV) when zero'ing to the Fermi level.

I'm not a fan of automatically changing labels in this case, but it would be good to have custom label options. (E.g. I personally prefer my DOS intensity axis to be labelled "DOS".)

I propose that
- **dosplot** gains `--xlabel` and `--ylabel` arguments
- **bandplot** gains `--ylabel` and `--doslabel` (for combined band/dos plots)

**Comment by utf** [comment]
Implemented in #11
