### ISSUE TITLE
DOS energies are shifted by SIGMA

### ISSUE THREAD

**Issue by yw-fang** [SMTG-UCL/sumo#90]
@utf  Hi, Alex, I am wondering why did you subtract the SIGMA from the dos.energies when ISMAR is among -1, 0 and 1?
Although in DFT calculations, we can use quite a small sigma (very close to 0) with the corresponding high k-meshes so that the values of dos.energies are almost unchanged; in many other cases, the values of SIGMA we use are not so small. 
(Note that, we don't consider the usually recommended tetrahedron method (ISMEAR=-5) of DOS calculations in this discussion.)

For example, when I was comparing the DOS from sumo with the DOS extracted using my own script this morning, I always found a shift on the axis of energy (see the figure). One can find that this shift is not so small: in the DOS by sumo,  there is a DOS peak at the Fermi level, while in the case processed by my own script, the DOS peak is shifted to the right-hand side of the Fermi level. Such a difference is not neglected. Just now I finally figured it out, and confirmed it was caused by the subtraction of SIGMA of 0.05 eV from the dos.energies due to the following code segment, could you make some comments? Thank you very much!

>     if vr.parameters['ISMEAR'] in [-1, 0, 1]:
>         dos.energies -= vr.parameters['SIGMA']
>         print("vr.parameters['SIGMA'] is", vr.parameters['SIGMA'])

![image](https://user-images.githubusercontent.com/16239703/70218627-acc6fd00-1786-11ea-8865-704d81bcf265.png)

**Comment by ajjackson** [comment]
This is well-timed, as we recently discussed removing this behaviour which was inherited from Sumo's predecessor. The original motive was to obtain a neater alignment between the DOS edges and zero but as you point out this can be misleading/unhelpful if the smearing is large. It also creates issues when plotting a DOS and band structure together.

As we also have the proposal https://github.com/SMTG-UCL/sumo/pull/68 to allow alignment to E_Fermi, it might make sense to implement such changes at the same time.

**Comment by yw-fang** [comment]
Agree, thank you very much for your quick comment!

**Comment by ajjackson** [comment]
I _think_ this is fixed now? Would be worth checking, it has been a while and a few things have changed 😅

**Comment by yw-fang** [comment]
Thanks very much, Adam. @ajjackson 
I just moved from Japan to Spain last month, and haven't completely settle down (everything is slow here). The schedure is tight because many things are postponed in the past weeks, but I'll try to check in the coming days and get back to you as soon as possible.

**Comment by ajjackson** [comment]
It sounds like you have far more important things to worry about! I hope things go smoothly.

**Comment by utf** [comment]
I believe this is fixed.
