### ISSUE TITLE
Fermi level from a dense k-mesh

### ISSUE THREAD

**Issue by pamukb** [SMTG-UCL/sumo#98]
Hello! I would like sumo to get the Fermi level from a calculation of dense k-mesh, which is more accurate, not from a calculation of bands along the high-symmetry lines. Is this possible? Thanks for your work!

**Comment by pamukb** [comment]
I found discussion [#68](https://github.com/SMTG-UCL/sumo/pull/68) also related. I think if you can allow the user the set the Fermi level as input, that would be ideal. Thanks!

**Comment by utf** [comment]
@pamukb This should be relatively easy to add. Thank you for the suggestion.

@ajjackson Yeah, a catch-up about this sounds good, I'll message you offline.

**Comment by ajjackson** [comment]
Hi @pamukb 

Just an update to say that it is now possible to set a user-specified reference energy with `--zero-energy`. This can be accessed via a Developer installation (it's on Master already) now, and will be in the next PyPI release.

Happy computing,
Adam
